<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>carpeta-pluginsib-carpetafront</artifactId>
    <packaging>pom</packaging>

    <parent>
        <groupId>es.caib.carpeta</groupId>
        <version>1.1.31</version>
        <artifactId>carpeta-pluginsib</artifactId>
    </parent>

    <name>Carpeta - PluginsIB - Carpeta Front</name>
    <modules>

        <module>api</module>
        <module>sistra</module>
        <module>regweb32</module>
        <module>notib2client</module>
        <module>notib</module>
        <module>notificacionssistra</module>
        <module>dadeslogin</module>
        <module>pinbalpolicia</module>
        <module>regwebdetallcomponent</module>
        <module>reprendretramitsistra</module>
        <module>pinbalayudasubvenciones</module>
        <module>pinbalfamilia</module>
        <module>pinbalcontrataciones</module>
        <module>pinbaldiscapacidad</module>
        <module>pinbalmatricula</module>
        <module>pinbalconvivencia</module>
        <module>pinbalhistorico</module>
        <module>apodera</module>
        <module>expedients</module>
        <module>certificats</module>
        <module>reactjschecker</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>es.caib.pinbal</groupId>
                <artifactId>pinbal-client</artifactId>
                <version>1.4.36</version>
                <exclusions>
                    <!-- evitar conflicte amb JAX-RS de JBoss -->
                    <exclusion>
                        <groupId>javax.ws.rs</groupId>
                        <artifactId>jsr311-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.core.v3</groupId>
            <artifactId>pluginsib-core</artifactId>
            <version>${pluginsib.core.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
