

# Dialecte de Hibernate
es.caib.carpeta.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# es.caib.carpeta.hibernate.dialect=org.hibernate.dialect.MySQLDialect      
# es.caib.carpeta.hibernate.dialect=org.hibernate.dialect.DB2Dialect
# es.caib.carpeta.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# es.caib.carpeta.hibernate.dialect=net.sf.hibernate.dialect.Oracle9Dialect

# es.caib.carpeta.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
# es.caib.carpeta.hibernate.query.substitutions=true 1, false 0
es.caib.carpeta.hibernate.show_sql=false
es.caib.carpeta.hibernate.format_sql=false


# Propietat que indica als projectes que activin les caracteristiques
# especials requerides en l'entorn de la CAIB (Govern Balear) si val true -->
es.caib.carpeta.iscaib=false




es.caib.carpeta.defaultlanguage=ca

es.caib.carpeta.development=false

#  Clau per encriptar l'identificador del fitxers a descarregar via web(IMPORTANT tamany de 16 caràcters) -->
es.caib.carpeta.encryptkey=carpeta1carpeta1

#  Llistat de Plugins per l'exportació de dades en els llistats (excel, ods, csv, ...) -->
# es.caib.carpeta.exportdataplugins=org.fundaciobit.plugins.exportdata.cvs.CSVPlugin,org.fundaciobit.plugins.exportdata.ods.ODSPlugin,org.fundaciobit.plugins.exportdata.excel.ExcelPlugin

#   Afegir aqui altres propietats 

# =========== PROPIETATS PEL FRONT ================ #

# PLUGIN DE LOGIN MOCK
#es.caib.carpeta.pluginsib.login.class=es.caib.carpeta.front.pluginlogin.PluginLoginMock
# Persona Fisica
#es.caib.carpeta.pluginsib.login.mock.logininfo={"username":"pfuster","name":"Pep","surname1":"Fuster","surname2":"Gonella","administrationID":"30000056Y","authenticationMethod":"None","qaa":1,"identityProvider":"MOCK","business":false}
# Persona Juridica
#es.caib.carpeta.pluginsib.login.mock.logininfo={"username":"","name":"MyBusiness","administrationID":"87654321Z","authenticationMethod":"None","qaa":1,"identityProvider":"MOCK","business":false,"representative":{"name":"Pep","surname1":"Gonella","surname2":"Fuster","administrationID":"30000056Y"}}



