/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AppInfo
 */



public class AppInfo {
  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("versio")
  private String versio = null;

  @JsonProperty("data")
  private String data = null;

  public AppInfo nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom de l&#x27;aplicació
   * @return nom
  **/
  @Schema(example = "Notib", description = "Nom de l'aplicació")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public AppInfo versio(String versio) {
    this.versio = versio;
    return this;
  }

   /**
   * Versió de l&#x27;aplicació
   * @return versio
  **/
  @Schema(example = "2.0.1", description = "Versió de l'aplicació")
  public String getVersio() {
    return versio;
  }

  public void setVersio(String versio) {
    this.versio = versio;
  }

  public AppInfo data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Data de compilació de l&#x27;aplicació
   * @return data
  **/
  @Schema(example = "2023-05-29T11:36:55Z", description = "Data de compilació de l'aplicació")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppInfo appInfo = (AppInfo) o;
    return Objects.equals(this.nom, appInfo.nom) &&
        Objects.equals(this.versio, appInfo.versio) &&
        Objects.equals(this.data, appInfo.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nom, versio, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppInfo {\n");
    
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    versio: ").append(toIndentedString(versio)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
