/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Arxiu
 */
@JsonPropertyOrder({
  Arxiu.JSON_PROPERTY_NOM,
  Arxiu.JSON_PROPERTY_MEDIA_TYPE,
  Arxiu.JSON_PROPERTY_CONTINGUT,
  Arxiu.JSON_PROPERTY_ERROR,
  Arxiu.JSON_PROPERTY_MISSATGE_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Arxiu {
  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_MEDIA_TYPE = "mediaType";
  private String mediaType;

  public static final String JSON_PROPERTY_CONTINGUT = "contingut";
  private String contingut;

  public static final String JSON_PROPERTY_ERROR = "error";
  private Boolean error;

  public static final String JSON_PROPERTY_MISSATGE_ERROR = "missatgeError";
  private String missatgeError;

  public Arxiu() {
  }

  public Arxiu nom(String nom) {
    
    this.nom = nom;
    return this;
  }

   /**
   * Nom de l&#39;arxiu&#39;
   * @return nom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public Arxiu mediaType(String mediaType) {
    
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Tipus d&#39;arxiu
   * @return mediaType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEDIA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMediaType() {
    return mediaType;
  }


  @JsonProperty(JSON_PROPERTY_MEDIA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMediaType(String mediaType) {
    this.mediaType = mediaType;
  }


  public Arxiu contingut(String contingut) {
    
    this.contingut = contingut;
    return this;
  }

   /**
   * Contingut de l&#39;arxiu en Base64
   * @return contingut
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTINGUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContingut() {
    return contingut;
  }


  @JsonProperty(JSON_PROPERTY_CONTINGUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContingut(String contingut) {
    this.contingut = contingut;
  }


  public Arxiu error(Boolean error) {
    
    this.error = error;
    return this;
  }

   /**
   * Indica si s&#39;ha produït un error al intentar recuperar l&#39;arxiu
   * @return error
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(Boolean error) {
    this.error = error;
  }


  public Arxiu missatgeError(String missatgeError) {
    
    this.missatgeError = missatgeError;
    return this;
  }

   /**
   * Descripció de l&#39;error
   * @return missatgeError
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MISSATGE_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMissatgeError() {
    return missatgeError;
  }


  @JsonProperty(JSON_PROPERTY_MISSATGE_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMissatgeError(String missatgeError) {
    this.missatgeError = missatgeError;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Arxiu arxiu = (Arxiu) o;
    return Objects.equals(this.nom, arxiu.nom) &&
        Objects.equals(this.mediaType, arxiu.mediaType) &&
        Objects.equals(this.contingut, arxiu.contingut) &&
        Objects.equals(this.error, arxiu.error) &&
        Objects.equals(this.missatgeError, arxiu.missatgeError);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nom, mediaType, contingut, error, missatgeError);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Arxiu {\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    contingut: ").append(toIndentedString(contingut)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    missatgeError: ").append(toIndentedString(missatgeError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

