/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Arxiu
 */



public class Arxiu {
  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("mediaType")
  private String mediaType = null;

  @JsonProperty("contingut")
  private String contingut = null;

  @JsonProperty("error")
  private Boolean error = null;

  @JsonProperty("missatgeError")
  private String missatgeError = null;

  public Arxiu nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom de l&#x27;arxiu&#x27;
   * @return nom
  **/
  @Schema(example = "document.pdf", description = "Nom de l'arxiu'")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public Arxiu mediaType(String mediaType) {
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Tipus d&#x27;arxiu
   * @return mediaType
  **/
  @Schema(example = "codi", description = "Tipus d'arxiu")
  public String getMediaType() {
    return mediaType;
  }

  public void setMediaType(String mediaType) {
    this.mediaType = mediaType;
  }

  public Arxiu contingut(String contingut) {
    this.contingut = contingut;
    return this;
  }

   /**
   * Contingut de l&#x27;arxiu en Base64
   * @return contingut
  **/
  @Schema(example = "codi", description = "Contingut de l'arxiu en Base64")
  public String getContingut() {
    return contingut;
  }

  public void setContingut(String contingut) {
    this.contingut = contingut;
  }

  public Arxiu error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Indica si s&#x27;ha produït un error al intentar recuperar l&#x27;arxiu
   * @return error
  **/
  @Schema(example = "false", description = "Indica si s'ha produït un error al intentar recuperar l'arxiu")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public Arxiu missatgeError(String missatgeError) {
    this.missatgeError = missatgeError;
    return this;
  }

   /**
   * Descripció de l&#x27;error
   * @return missatgeError
  **/
  @Schema(example = "No s'ha trobat el document.", description = "Descripció de l'error")
  public String getMissatgeError() {
    return missatgeError;
  }

  public void setMissatgeError(String missatgeError) {
    this.missatgeError = missatgeError;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Arxiu arxiu = (Arxiu) o;
    return Objects.equals(this.nom, arxiu.nom) &&
        Objects.equals(this.mediaType, arxiu.mediaType) &&
        Objects.equals(this.contingut, arxiu.contingut) &&
        Objects.equals(this.error, arxiu.error) &&
        Objects.equals(this.missatgeError, arxiu.missatgeError);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nom, mediaType, contingut, error, missatgeError);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Arxiu {\n");
    
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    contingut: ").append(toIndentedString(contingut)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    missatgeError: ").append(toIndentedString(missatgeError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
