/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.joda.time.DateTime;
/**
 * Informació de la certificació realitzada a Notific@
 */
@Schema(description = "Informació de la certificació realitzada a Notific@")


public class Certificacio {
  @JsonProperty("data")
  private DateTime data = null;

  @JsonProperty("origen")
  private String origen = null;

  @JsonProperty("contingutBase64")
  private String contingutBase64 = null;

  @JsonProperty("tamany")
  private Integer tamany = null;

  @JsonProperty("hash")
  private String hash = null;

  @JsonProperty("metadades")
  private String metadades = null;

  @JsonProperty("csv")
  private String csv = null;

  @JsonProperty("tipusMime")
  private String tipusMime = null;

  public Certificacio data(DateTime data) {
    this.data = data;
    return this;
  }

   /**
   * Data de creació de la certificació de la notificació
   * @return data
  **/
  @Schema(description = "Data de creació de la certificació de la notificació")
  public DateTime getData() {
    return data;
  }

  public void setData(DateTime data) {
    this.data = data;
  }

  public Certificacio origen(String origen) {
    this.origen = origen;
    return this;
  }

   /**
   * Origen de la certificació
   * @return origen
  **/
  @Schema(example = "carpeta", description = "Origen de la certificació")
  public String getOrigen() {
    return origen;
  }

  public void setOrigen(String origen) {
    this.origen = origen;
  }

  public Certificacio contingutBase64(String contingutBase64) {
    this.contingutBase64 = contingutBase64;
    return this;
  }

   /**
   * Contingut de la certificació en Base64.
   * @return contingutBase64
  **/
  @Schema(example = "JVBERi0xLjYKJcOkw7zDtsOfCjIgMCBv==", description = "Contingut de la certificació en Base64.")
  public String getContingutBase64() {
    return contingutBase64;
  }

  public void setContingutBase64(String contingutBase64) {
    this.contingutBase64 = contingutBase64;
  }

  public Certificacio tamany(Integer tamany) {
    this.tamany = tamany;
    return this;
  }

   /**
   * Mida de la certificació
   * @return tamany
  **/
  @Schema(example = "4265384", description = "Mida de la certificació")
  public Integer getTamany() {
    return tamany;
  }

  public void setTamany(Integer tamany) {
    this.tamany = tamany;
  }

  public Certificacio hash(String hash) {
    this.hash = hash;
    return this;
  }

   /**
   * Hash de la certificació
   * @return hash
  **/
  @Schema(example = "00000000", description = "Hash de la certificació")
  public String getHash() {
    return hash;
  }

  public void setHash(String hash) {
    this.hash = hash;
  }

  public Certificacio metadades(String metadades) {
    this.metadades = metadades;
    return this;
  }

   /**
   * Metadades de la certificació
   * @return metadades
  **/
  @Schema(example = "00000000", description = "Metadades de la certificació")
  public String getMetadades() {
    return metadades;
  }

  public void setMetadades(String metadades) {
    this.metadades = metadades;
  }

  public Certificacio csv(String csv) {
    this.csv = csv;
    return this;
  }

   /**
   * Codi CSV de la certificació
   * @return csv
  **/
  @Schema(example = "aa10b27d8e221cf923715f01e01f515fa7cfec1322b6b49644a27a00461defea", description = "Codi CSV de la certificació")
  public String getCsv() {
    return csv;
  }

  public void setCsv(String csv) {
    this.csv = csv;
  }

  public Certificacio tipusMime(String tipusMime) {
    this.tipusMime = tipusMime;
    return this;
  }

   /**
   * Tipus MIME de la certificació
   * @return tipusMime
  **/
  @Schema(example = "application/pdf", description = "Tipus MIME de la certificació")
  public String getTipusMime() {
    return tipusMime;
  }

  public void setTipusMime(String tipusMime) {
    this.tipusMime = tipusMime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Certificacio certificacio = (Certificacio) o;
    return Objects.equals(this.data, certificacio.data) &&
        Objects.equals(this.origen, certificacio.origen) &&
        Objects.equals(this.contingutBase64, certificacio.contingutBase64) &&
        Objects.equals(this.tamany, certificacio.tamany) &&
        Objects.equals(this.hash, certificacio.hash) &&
        Objects.equals(this.metadades, certificacio.metadades) &&
        Objects.equals(this.csv, certificacio.csv) &&
        Objects.equals(this.tipusMime, certificacio.tipusMime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, origen, contingutBase64, tamany, hash, metadades, csv, tipusMime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Certificacio {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    origen: ").append(toIndentedString(origen)).append("\n");
    sb.append("    contingutBase64: ").append(toIndentedString(contingutBase64)).append("\n");
    sb.append("    tamany: ").append(toIndentedString(tamany)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    metadades: ").append(toIndentedString(metadades)).append("\n");
    sb.append("    csv: ").append(toIndentedString(csv)).append("\n");
    sb.append("    tipusMime: ").append(toIndentedString(tipusMime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
