/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació de la certificació realitzada a Notific@
 */
@JsonPropertyOrder({
  Certificacio.JSON_PROPERTY_DATA,
  Certificacio.JSON_PROPERTY_ORIGEN,
  Certificacio.JSON_PROPERTY_CONTINGUT_BASE64,
  Certificacio.JSON_PROPERTY_TAMANY,
  Certificacio.JSON_PROPERTY_HASH,
  Certificacio.JSON_PROPERTY_METADADES,
  Certificacio.JSON_PROPERTY_CSV,
  Certificacio.JSON_PROPERTY_TIPUS_MIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Certificacio {
  public static final String JSON_PROPERTY_DATA = "data";
  private Long data;

  public static final String JSON_PROPERTY_ORIGEN = "origen";
  private String origen;

  public static final String JSON_PROPERTY_CONTINGUT_BASE64 = "contingutBase64";
  private String contingutBase64;

  public static final String JSON_PROPERTY_TAMANY = "tamany";
  private Integer tamany;

  public static final String JSON_PROPERTY_HASH = "hash";
  private String hash;

  public static final String JSON_PROPERTY_METADADES = "metadades";
  private String metadades;

  public static final String JSON_PROPERTY_CSV = "csv";
  private String csv;

  public static final String JSON_PROPERTY_TIPUS_MIME = "tipusMime";
  private String tipusMime;

  public Certificacio() {
  }

  public Certificacio data(Long data) {
    
    this.data = data;
    return this;
  }

   /**
   * Data de creació de la certificació de la notificació
   * @return data
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(Long data) {
    this.data = data;
  }


  public Certificacio origen(String origen) {
    
    this.origen = origen;
    return this;
  }

   /**
   * Origen de la certificació
   * @return origen
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrigen() {
    return origen;
  }


  @JsonProperty(JSON_PROPERTY_ORIGEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrigen(String origen) {
    this.origen = origen;
  }


  public Certificacio contingutBase64(String contingutBase64) {
    
    this.contingutBase64 = contingutBase64;
    return this;
  }

   /**
   * Contingut de la certificació en Base64.
   * @return contingutBase64
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTINGUT_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContingutBase64() {
    return contingutBase64;
  }


  @JsonProperty(JSON_PROPERTY_CONTINGUT_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContingutBase64(String contingutBase64) {
    this.contingutBase64 = contingutBase64;
  }


  public Certificacio tamany(Integer tamany) {
    
    this.tamany = tamany;
    return this;
  }

   /**
   * Mida de la certificació
   * @return tamany
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAMANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTamany() {
    return tamany;
  }


  @JsonProperty(JSON_PROPERTY_TAMANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTamany(Integer tamany) {
    this.tamany = tamany;
  }


  public Certificacio hash(String hash) {
    
    this.hash = hash;
    return this;
  }

   /**
   * Hash de la certificació
   * @return hash
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHash() {
    return hash;
  }


  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHash(String hash) {
    this.hash = hash;
  }


  public Certificacio metadades(String metadades) {
    
    this.metadades = metadades;
    return this;
  }

   /**
   * Metadades de la certificació
   * @return metadades
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADADES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetadades() {
    return metadades;
  }


  @JsonProperty(JSON_PROPERTY_METADADES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadades(String metadades) {
    this.metadades = metadades;
  }


  public Certificacio csv(String csv) {
    
    this.csv = csv;
    return this;
  }

   /**
   * Codi CSV de la certificació
   * @return csv
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CSV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCsv() {
    return csv;
  }


  @JsonProperty(JSON_PROPERTY_CSV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCsv(String csv) {
    this.csv = csv;
  }


  public Certificacio tipusMime(String tipusMime) {
    
    this.tipusMime = tipusMime;
    return this;
  }

   /**
   * Tipus MIME de la certificació
   * @return tipusMime
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIPUS_MIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTipusMime() {
    return tipusMime;
  }


  @JsonProperty(JSON_PROPERTY_TIPUS_MIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTipusMime(String tipusMime) {
    this.tipusMime = tipusMime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Certificacio certificacio = (Certificacio) o;
    return Objects.equals(this.data, certificacio.data) &&
        Objects.equals(this.origen, certificacio.origen) &&
        Objects.equals(this.contingutBase64, certificacio.contingutBase64) &&
        Objects.equals(this.tamany, certificacio.tamany) &&
        Objects.equals(this.hash, certificacio.hash) &&
        Objects.equals(this.metadades, certificacio.metadades) &&
        Objects.equals(this.csv, certificacio.csv) &&
        Objects.equals(this.tipusMime, certificacio.tipusMime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, origen, contingutBase64, tamany, hash, metadades, csv, tipusMime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Certificacio {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    origen: ").append(toIndentedString(origen)).append("\n");
    sb.append("    contingutBase64: ").append(toIndentedString(contingutBase64)).append("\n");
    sb.append("    tamany: ").append(toIndentedString(tamany)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    metadades: ").append(toIndentedString(metadades)).append("\n");
    sb.append("    csv: ").append(toIndentedString(csv)).append("\n");
    sb.append("    tipusMime: ").append(toIndentedString(tipusMime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

