/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Objecte amb les dades necessàries per consultar les dades de registre d&#39;una notificació o enviament
 */
@JsonPropertyOrder({
  DadesConsulta.JSON_PROPERTY_IDENTIFICADOR,
  DadesConsulta.JSON_PROPERTY_REFERENCIA,
  DadesConsulta.JSON_PROPERTY_AMB_JUSTIFICANT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DadesConsulta {
  public static final String JSON_PROPERTY_IDENTIFICADOR = "identificador";
  private String identificador;

  public static final String JSON_PROPERTY_REFERENCIA = "referencia";
  private String referencia;

  public static final String JSON_PROPERTY_AMB_JUSTIFICANT = "ambJustificant";
  private String ambJustificant;

  public DadesConsulta() {
  }

  public DadesConsulta identificador(String identificador) {
    
    this.identificador = identificador;
    return this;
  }

   /**
   * Identificador únic de la notificació a consultar  * Camp mantingut únicament per compatibilitat amb versions antigues  * S&#39;ha d&#39;indicar un idientificador o una referència. En cas d&#39;informar ambdós, només es tindrà en compte l&#39;identificador. Es recomana cercar sempre per referència
   * @return identificador
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFICADOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentificador() {
    return identificador;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFICADOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificador(String identificador) {
    this.identificador = identificador;
  }


  public DadesConsulta referencia(String referencia) {
    
    this.referencia = referencia;
    return this;
  }

   /**
   * Referència (identificador) única de l&#39;enviament que es vol consultar  * S&#39;ha d&#39;indicar un idientificador o una referència. En cas d&#39;informar ambdós, només es tindrà en compte l&#39;identificador.  * Es recomana cercar sempre per referència
   * @return referencia
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferencia() {
    return referencia;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferencia(String referencia) {
    this.referencia = referencia;
  }


  public DadesConsulta ambJustificant(String ambJustificant) {
    
    this.ambJustificant = ambJustificant;
    return this;
  }

   /**
   * Indica si a la resposta s&#39;ha d&#39;incloure el justificant de registre
   * @return ambJustificant
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMB_JUSTIFICANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAmbJustificant() {
    return ambJustificant;
  }


  @JsonProperty(JSON_PROPERTY_AMB_JUSTIFICANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmbJustificant(String ambJustificant) {
    this.ambJustificant = ambJustificant;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadesConsulta dadesConsulta = (DadesConsulta) o;
    return Objects.equals(this.identificador, dadesConsulta.identificador) &&
        Objects.equals(this.referencia, dadesConsulta.referencia) &&
        Objects.equals(this.ambJustificant, dadesConsulta.ambJustificant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificador, referencia, ambJustificant);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadesConsulta {\n");
    sb.append("    identificador: ").append(toIndentedString(identificador)).append("\n");
    sb.append("    referencia: ").append(toIndentedString(referencia)).append("\n");
    sb.append("    ambJustificant: ").append(toIndentedString(ambJustificant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

