/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Document notificat
 */
@Schema(description = "Document notificat")


public class DocumentConsultaV2 {
  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("mediaType")
  private String mediaType = null;

  @JsonProperty("mida")
  private Long mida = null;

  @JsonProperty("url")
  private String url = null;

  public DocumentConsultaV2 nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom del document
   * @return nom
  **/
  @Schema(example = "document.pdf", description = "Nom del document")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public DocumentConsultaV2 mediaType(String mediaType) {
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Tipus de document
   * @return mediaType
  **/
  @Schema(example = "application/pdf", description = "Tipus de document")
  public String getMediaType() {
    return mediaType;
  }

  public void setMediaType(String mediaType) {
    this.mediaType = mediaType;
  }

  public DocumentConsultaV2 mida(Long mida) {
    this.mida = mida;
    return this;
  }

   /**
   * Mida del document
   * @return mida
  **/
  @Schema(example = "4532", description = "Mida del document")
  public Long getMida() {
    return mida;
  }

  public void setMida(Long mida) {
    this.mida = mida;
  }

  public DocumentConsultaV2 url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Url per a la descàrrega del document
   * @return url
  **/
  @Schema(example = "http://localhost:8080/notibapi/interna/v2/document/00000000-0000-0000-0000-000000000000", description = "Url per a la descàrrega del document")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentConsultaV2 documentConsultaV2 = (DocumentConsultaV2) o;
    return Objects.equals(this.nom, documentConsultaV2.nom) &&
        Objects.equals(this.mediaType, documentConsultaV2.mediaType) &&
        Objects.equals(this.mida, documentConsultaV2.mida) &&
        Objects.equals(this.url, documentConsultaV2.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nom, mediaType, mida, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentConsultaV2 {\n");
    
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    mida: ").append(toIndentedString(mida)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
