/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Document notificat
 */
@JsonPropertyOrder({
  DocumentConsultaV2.JSON_PROPERTY_NOM,
  DocumentConsultaV2.JSON_PROPERTY_MEDIA_TYPE,
  DocumentConsultaV2.JSON_PROPERTY_MIDA,
  DocumentConsultaV2.JSON_PROPERTY_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DocumentConsultaV2 {
  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_MEDIA_TYPE = "mediaType";
  private String mediaType;

  public static final String JSON_PROPERTY_MIDA = "mida";
  private Long mida;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public DocumentConsultaV2() {
  }

  public DocumentConsultaV2 nom(String nom) {
    
    this.nom = nom;
    return this;
  }

   /**
   * Nom del document
   * @return nom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public DocumentConsultaV2 mediaType(String mediaType) {
    
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Tipus de document
   * @return mediaType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEDIA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMediaType() {
    return mediaType;
  }


  @JsonProperty(JSON_PROPERTY_MEDIA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMediaType(String mediaType) {
    this.mediaType = mediaType;
  }


  public DocumentConsultaV2 mida(Long mida) {
    
    this.mida = mida;
    return this;
  }

   /**
   * Mida del document
   * @return mida
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIDA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMida() {
    return mida;
  }


  @JsonProperty(JSON_PROPERTY_MIDA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMida(Long mida) {
    this.mida = mida;
  }


  public DocumentConsultaV2 url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Url per a la descàrrega del document
   * @return url
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentConsultaV2 documentConsultaV2 = (DocumentConsultaV2) o;
    return Objects.equals(this.nom, documentConsultaV2.nom) &&
        Objects.equals(this.mediaType, documentConsultaV2.mediaType) &&
        Objects.equals(this.mida, documentConsultaV2.mida) &&
        Objects.equals(this.url, documentConsultaV2.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nom, mediaType, mida, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentConsultaV2 {\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    mida: ").append(toIndentedString(mida)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

