/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Identificador del procediment SIA al que pertany la notificació * Obligatori únicament en cas d&#39;indicar que es realitza entrega DEH __Actualment en desús amb l&#39;entrada en funcionament de la DEHú__
 */
@JsonPropertyOrder({
  EntregaDeh.JSON_PROPERTY_OBLIGAT,
  EntregaDeh.JSON_PROPERTY_PROCEDIMENT_CODI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EntregaDeh {
  public static final String JSON_PROPERTY_OBLIGAT = "obligat";
  private Boolean obligat = false;

  public static final String JSON_PROPERTY_PROCEDIMENT_CODI = "procedimentCodi";
  private String procedimentCodi;

  public EntregaDeh() {
  }

  public EntregaDeh obligat(Boolean obligat) {
    
    this.obligat = obligat;
    return this;
  }

   /**
   * Indica si l’enviament és obligatori o voluntari
   * @return obligat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBLIGAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isObligat() {
    return obligat;
  }


  @JsonProperty(JSON_PROPERTY_OBLIGAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObligat(Boolean obligat) {
    this.obligat = obligat;
  }


  public EntregaDeh procedimentCodi(String procedimentCodi) {
    
    this.procedimentCodi = procedimentCodi;
    return this;
  }

   /**
   * Codi del procediment a la DEH per a enviaments voluntaris.  * Aquest camp NO s&#39;utilitza, sinó que s’agafa el codi del procediment de la notificació. (Es manté únicament per compatibilitat amb els serveis de Notific@)
   * @return procedimentCodi
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCEDIMENT_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcedimentCodi() {
    return procedimentCodi;
  }


  @JsonProperty(JSON_PROPERTY_PROCEDIMENT_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcedimentCodi(String procedimentCodi) {
    this.procedimentCodi = procedimentCodi;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntregaDeh entregaDeh = (EntregaDeh) o;
    return Objects.equals(this.obligat, entregaDeh.obligat) &&
        Objects.equals(this.procedimentCodi, entregaDeh.procedimentCodi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(obligat, procedimentCodi);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntregaDeh {\n");
    sb.append("    obligat: ").append(toIndentedString(obligat)).append("\n");
    sb.append("    procedimentCodi: ").append(toIndentedString(procedimentCodi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

