/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Objecte amb les dades necessàries per a realitzar una entrega postal  * Obligatori únicament en cas d&#x27;indicar que es realitza entrega postal(Consultar prèviament si està disponible l&#x27;entrega postal a l&#x27;òrgan gestor emissor)
 */
@Schema(description = "Objecte amb les dades necessàries per a realitzar una entrega postal  * Obligatori únicament en cas d'indicar que es realitza entrega postal(Consultar prèviament si està disponible l'entrega postal a l'òrgan gestor emissor)")


public class EntregaPostal {
  /**
   * Enumerat que indica el tipus de entrega postal.
   */
  public enum TipusEnum {
    NACIONAL("NACIONAL"),
    ESTRANGER("ESTRANGER"),
    APARTAT_CORREUS("APARTAT_CORREUS"),
    SENSE_NORMALITZAR("SENSE_NORMALITZAR");

    private String value;

    TipusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TipusEnum fromValue(String input) {
      for (TipusEnum b : TipusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("tipus")
  private TipusEnum tipus = null;

  /**
   * Enumerat que indica el tipus de via per a entregues postals  * Obligatori quan tipoDomicili &#x3D; NACIONAL
   */
  public enum ViaTipusEnum {
    ALAMEDA("ALAMEDA"),
    CALLE("CALLE"),
    CAMINO("CAMINO"),
    CARRER("CARRER"),
    CARRETERA("CARRETERA"),
    GLORIETA("GLORIETA"),
    KALEA("KALEA"),
    PASAJE("PASAJE"),
    PASEO("PASEO"),
    PLA_A("PLAÇA"),
    PLAZA("PLAZA"),
    RAMBLA("RAMBLA"),
    RONDA("RONDA"),
    RUA("RUA"),
    SECTOR("SECTOR"),
    TRAVESIA("TRAVESIA"),
    URBANIZACION("URBANIZACION"),
    AVENIDA("AVENIDA"),
    AVINGUDA("AVINGUDA"),
    BARRIO("BARRIO"),
    CALLEJA("CALLEJA"),
    CAMI("CAMI"),
    CAMPO("CAMPO"),
    CARRERA("CARRERA"),
    CUESTA("CUESTA"),
    EDIFICIO("EDIFICIO"),
    ENPARANTZA("ENPARANTZA"),
    ESTRADA("ESTRADA"),
    JARDINES("JARDINES"),
    JARDINS("JARDINS"),
    PARQUE("PARQUE"),
    PASSEIG("PASSEIG"),
    PRAZA("PRAZA"),
    PLAZUELA("PLAZUELA"),
    PLACETA("PLACETA"),
    POBLADO("POBLADO"),
    VIA("VIA"),
    TRAVESSERA("TRAVESSERA"),
    PASSATGE("PASSATGE"),
    BULEVAR("BULEVAR"),
    POLIGONO("POLIGONO"),
    OTROS("OTROS");

    private String value;

    ViaTipusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ViaTipusEnum fromValue(String input) {
      for (ViaTipusEnum b : ViaTipusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("viaTipus")
  private ViaTipusEnum viaTipus = null;

  @JsonProperty("viaNom")
  private String viaNom = null;

  @JsonProperty("numeroCasa")
  private String numeroCasa = null;

  @JsonProperty("numeroQualificador")
  private String numeroQualificador = null;

  @JsonProperty("puntKm")
  private String puntKm = null;

  @JsonProperty("apartatCorreus")
  private String apartatCorreus = null;

  @JsonProperty("portal")
  private String portal = null;

  @JsonProperty("escala")
  private String escala = null;

  @JsonProperty("planta")
  private String planta = null;

  @JsonProperty("porta")
  private String porta = null;

  @JsonProperty("bloc")
  private String bloc = null;

  @JsonProperty("complement")
  private String complement = null;

  @JsonProperty("codiPostal")
  private String codiPostal = null;

  @JsonProperty("poblacio")
  private String poblacio = null;

  @JsonProperty("municipiCodi")
  private String municipiCodi = null;

  @JsonProperty("provincia")
  private String provincia = null;

  @JsonProperty("paisCodi")
  private String paisCodi = null;

  @JsonProperty("linea1")
  private String linea1 = null;

  @JsonProperty("linea2")
  private String linea2 = null;

  @JsonProperty("cie")
  private String cie = null;

  @JsonProperty("formatSobre")
  private String formatSobre = null;

  @JsonProperty("formatFulla")
  private String formatFulla = null;

  public EntregaPostal tipus(TipusEnum tipus) {
    this.tipus = tipus;
    return this;
  }

   /**
   * Enumerat que indica el tipus de entrega postal.
   * @return tipus
  **/
  @Schema(example = "NACIONAL", required = true, description = "Enumerat que indica el tipus de entrega postal.")
  public TipusEnum getTipus() {
    return tipus;
  }

  public void setTipus(TipusEnum tipus) {
    this.tipus = tipus;
  }

  public EntregaPostal viaTipus(ViaTipusEnum viaTipus) {
    this.viaTipus = viaTipus;
    return this;
  }

   /**
   * Enumerat que indica el tipus de via per a entregues postals  * Obligatori quan tipoDomicili &#x3D; NACIONAL
   * @return viaTipus
  **/
  @Schema(example = "CARRER", description = "Enumerat que indica el tipus de via per a entregues postals  * Obligatori quan tipoDomicili = NACIONAL")
  public ViaTipusEnum getViaTipus() {
    return viaTipus;
  }

  public void setViaTipus(ViaTipusEnum viaTipus) {
    this.viaTipus = viaTipus;
  }

  public EntregaPostal viaNom(String viaNom) {
    this.viaNom = viaNom;
    return this;
  }

   /**
   * Nom de la via per entregues postals  * Obligatori quan tipoDomicili &#x3D; NACIONAL o ESTRANGER
   * @return viaNom
  **/
  @Schema(example = "Aragó", description = "Nom de la via per entregues postals  * Obligatori quan tipoDomicili = NACIONAL o ESTRANGER")
  public String getViaNom() {
    return viaNom;
  }

  public void setViaNom(String viaNom) {
    this.viaNom = viaNom;
  }

  public EntregaPostal numeroCasa(String numeroCasa) {
    this.numeroCasa = numeroCasa;
    return this;
  }

   /**
   * Número de la casa per entregues postals  * Obligatori quan tipoDomicili &#x3D; NACIONAL excepte si s’indica el punt quilomètric
   * @return numeroCasa
  **/
  @Schema(example = "26", description = "Número de la casa per entregues postals  * Obligatori quan tipoDomicili = NACIONAL excepte si s’indica el punt quilomètric")
  public String getNumeroCasa() {
    return numeroCasa;
  }

  public void setNumeroCasa(String numeroCasa) {
    this.numeroCasa = numeroCasa;
  }

  public EntregaPostal numeroQualificador(String numeroQualificador) {
    this.numeroQualificador = numeroQualificador;
    return this;
  }

   /**
   * Informació addicional sobre la numeració de l’adreça
   * @return numeroQualificador
  **/
  @Schema(example = "bis", description = "Informació addicional sobre la numeració de l’adreça")
  public String getNumeroQualificador() {
    return numeroQualificador;
  }

  public void setNumeroQualificador(String numeroQualificador) {
    this.numeroQualificador = numeroQualificador;
  }

  public EntregaPostal puntKm(String puntKm) {
    this.puntKm = puntKm;
    return this;
  }

   /**
   * Punt quilomètric per entregues postals  * Obligatori quan tipoDomicili &#x3D; NACIONAL excepte si s’indica numeroCasa
   * @return puntKm
  **/
  @Schema(example = "12.5", description = "Punt quilomètric per entregues postals  * Obligatori quan tipoDomicili = NACIONAL excepte si s’indica numeroCasa")
  public String getPuntKm() {
    return puntKm;
  }

  public void setPuntKm(String puntKm) {
    this.puntKm = puntKm;
  }

  public EntregaPostal apartatCorreus(String apartatCorreus) {
    this.apartatCorreus = apartatCorreus;
    return this;
  }

   /**
   * Apartat de correus per entregues postals  * Obligatori quan tipoDomicili &#x3D; APARTAT_CORREUS
   * @return apartatCorreus
  **/
  @Schema(example = "123", description = "Apartat de correus per entregues postals  * Obligatori quan tipoDomicili = APARTAT_CORREUS")
  public String getApartatCorreus() {
    return apartatCorreus;
  }

  public void setApartatCorreus(String apartatCorreus) {
    this.apartatCorreus = apartatCorreus;
  }

  public EntregaPostal portal(String portal) {
    this.portal = portal;
    return this;
  }

   /**
   * Portal de la casa per entregues postals
   * @return portal
  **/
  @Schema(example = "2", description = "Portal de la casa per entregues postals")
  public String getPortal() {
    return portal;
  }

  public void setPortal(String portal) {
    this.portal = portal;
  }

  public EntregaPostal escala(String escala) {
    this.escala = escala;
    return this;
  }

   /**
   * Escala de la casa per entregues postals
   * @return escala
  **/
  @Schema(example = "B", description = "Escala de la casa per entregues postals")
  public String getEscala() {
    return escala;
  }

  public void setEscala(String escala) {
    this.escala = escala;
  }

  public EntregaPostal planta(String planta) {
    this.planta = planta;
    return this;
  }

   /**
   * Planta de la casa per entregues postals
   * @return planta
  **/
  @Schema(example = "4", description = "Planta de la casa per entregues postals")
  public String getPlanta() {
    return planta;
  }

  public void setPlanta(String planta) {
    this.planta = planta;
  }

  public EntregaPostal porta(String porta) {
    this.porta = porta;
    return this;
  }

   /**
   * Porta de la casa per entregues postals
   * @return porta
  **/
  @Schema(example = "2", description = "Porta de la casa per entregues postals")
  public String getPorta() {
    return porta;
  }

  public void setPorta(String porta) {
    this.porta = porta;
  }

  public EntregaPostal bloc(String bloc) {
    this.bloc = bloc;
    return this;
  }

   /**
   * Bloc de la casa per entregues postals
   * @return bloc
  **/
  @Schema(example = "C", description = "Bloc de la casa per entregues postals")
  public String getBloc() {
    return bloc;
  }

  public void setBloc(String bloc) {
    this.bloc = bloc;
  }

  public EntregaPostal complement(String complement) {
    this.complement = complement;
    return this;
  }

   /**
   * Informació extra sobre la casa per entregues postals
   * @return complement
  **/
  @Schema(example = "Edificio Walden", description = "Informació extra sobre la casa per entregues postals")
  public String getComplement() {
    return complement;
  }

  public void setComplement(String complement) {
    this.complement = complement;
  }

  public EntregaPostal codiPostal(String codiPostal) {
    this.codiPostal = codiPostal;
    return this;
  }

   /**
   * Codi postal de la casa per entregues postals.  * Per enviaments internacionals a països sense codi posatal es pot posar 00000.
   * @return codiPostal
  **/
  @Schema(example = "07003", required = true, description = "Codi postal de la casa per entregues postals.  * Per enviaments internacionals a països sense codi posatal es pot posar 00000.")
  public String getCodiPostal() {
    return codiPostal;
  }

  public void setCodiPostal(String codiPostal) {
    this.codiPostal = codiPostal;
  }

  public EntregaPostal poblacio(String poblacio) {
    this.poblacio = poblacio;
    return this;
  }

   /**
   * Població on s’entrega l’enviament  * Obligatori quan tipoDomicili &#x3D; NACIONAL, ESTRANGER o APARTAT_POSTAL
   * @return poblacio
  **/
  @Schema(example = "Palma", description = "Població on s’entrega l’enviament  * Obligatori quan tipoDomicili = NACIONAL, ESTRANGER o APARTAT_POSTAL")
  public String getPoblacio() {
    return poblacio;
  }

  public void setPoblacio(String poblacio) {
    this.poblacio = poblacio;
  }

  public EntregaPostal municipiCodi(String municipiCodi) {
    this.municipiCodi = municipiCodi;
    return this;
  }

   /**
   * Codi INE de 6 caràcters del municipi on s’entrega l’enviament (inclou codi de control)  * Obligatori quan tipoDomicili &#x3D; NACIONAL o APARTAT_POSTAL
   * @return municipiCodi
  **/
  @Schema(example = "070407", description = "Codi INE de 6 caràcters del municipi on s’entrega l’enviament (inclou codi de control)  * Obligatori quan tipoDomicili = NACIONAL o APARTAT_POSTAL")
  public String getMunicipiCodi() {
    return municipiCodi;
  }

  public void setMunicipiCodi(String municipiCodi) {
    this.municipiCodi = municipiCodi;
  }

  public EntregaPostal provincia(String provincia) {
    this.provincia = provincia;
    return this;
  }

   /**
   * Codi INE de 2 dígits de la província on s’entrega l’enviament  * Obligatori quan tipoDomicili &#x3D; NACIONAL o APARTAT_POSTAL
   * @return provincia
  **/
  @Schema(example = "07", description = "Codi INE de 2 dígits de la província on s’entrega l’enviament  * Obligatori quan tipoDomicili = NACIONAL o APARTAT_POSTAL")
  public String getProvincia() {
    return provincia;
  }

  public void setProvincia(String provincia) {
    this.provincia = provincia;
  }

  public EntregaPostal paisCodi(String paisCodi) {
    this.paisCodi = paisCodi;
    return this;
  }

   /**
   * Codi ISO 3166 de 2 caràcters del país on s’entrega l’enviament * Obligatori quan tipoDomicili &#x3D; ESTRANGER
   * @return paisCodi
  **/
  @Schema(example = "DE", description = "Codi ISO 3166 de 2 caràcters del país on s’entrega l’enviament * Obligatori quan tipoDomicili = ESTRANGER")
  public String getPaisCodi() {
    return paisCodi;
  }

  public void setPaisCodi(String paisCodi) {
    this.paisCodi = paisCodi;
  }

  public EntregaPostal linea1(String linea1) {
    this.linea1 = linea1;
    return this;
  }

   /**
   * Línia 1 de l’adreça d’entrega de l’enviament sense normalitzar  * Obligatori quan tipoDomicili &#x3D; SENSE_NORMALITZAR
   * @return linea1
  **/
  @Schema(example = "Carrer Aragó 26bis, 4t - 3", description = "Línia 1 de l’adreça d’entrega de l’enviament sense normalitzar  * Obligatori quan tipoDomicili = SENSE_NORMALITZAR")
  public String getLinea1() {
    return linea1;
  }

  public void setLinea1(String linea1) {
    this.linea1 = linea1;
  }

  public EntregaPostal linea2(String linea2) {
    this.linea2 = linea2;
    return this;
  }

   /**
   * Línia 2 de l’adreça d’entrega de l’enviament sense normalitzar  * Obligatori quan tipoDomicili &#x3D; SENSE_NORMALITZAR
   * @return linea2
  **/
  @Schema(example = "Palma 07003 - Illes Balears", description = "Línia 2 de l’adreça d’entrega de l’enviament sense normalitzar  * Obligatori quan tipoDomicili = SENSE_NORMALITZAR")
  public String getLinea2() {
    return linea2;
  }

  public void setLinea2(String linea2) {
    this.linea2 = linea2;
  }

  public EntregaPostal cie(String cie) {
    this.cie = cie;
    return this;
  }

   /**
   * Línia 2 de l’adreça d’entrega de l’enviament sense normalitzar
   * @return cie
  **/
  @Schema(example = "Servera", description = "Línia 2 de l’adreça d’entrega de l’enviament sense normalitzar")
  public String getCie() {
    return cie;
  }

  public void setCie(String cie) {
    this.cie = cie;
  }

  public EntregaPostal formatSobre(String formatSobre) {
    this.formatSobre = formatSobre;
    return this;
  }

   /**
   * Cadena indicant el format del sobre 
   * @return formatSobre
  **/
  @Schema(example = "C5", description = "Cadena indicant el format del sobre ")
  public String getFormatSobre() {
    return formatSobre;
  }

  public void setFormatSobre(String formatSobre) {
    this.formatSobre = formatSobre;
  }

  public EntregaPostal formatFulla(String formatFulla) {
    this.formatFulla = formatFulla;
    return this;
  }

   /**
   * Cadena indicant el format de la fulla
   * @return formatFulla
  **/
  @Schema(example = "A4", description = "Cadena indicant el format de la fulla")
  public String getFormatFulla() {
    return formatFulla;
  }

  public void setFormatFulla(String formatFulla) {
    this.formatFulla = formatFulla;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntregaPostal entregaPostal = (EntregaPostal) o;
    return Objects.equals(this.tipus, entregaPostal.tipus) &&
        Objects.equals(this.viaTipus, entregaPostal.viaTipus) &&
        Objects.equals(this.viaNom, entregaPostal.viaNom) &&
        Objects.equals(this.numeroCasa, entregaPostal.numeroCasa) &&
        Objects.equals(this.numeroQualificador, entregaPostal.numeroQualificador) &&
        Objects.equals(this.puntKm, entregaPostal.puntKm) &&
        Objects.equals(this.apartatCorreus, entregaPostal.apartatCorreus) &&
        Objects.equals(this.portal, entregaPostal.portal) &&
        Objects.equals(this.escala, entregaPostal.escala) &&
        Objects.equals(this.planta, entregaPostal.planta) &&
        Objects.equals(this.porta, entregaPostal.porta) &&
        Objects.equals(this.bloc, entregaPostal.bloc) &&
        Objects.equals(this.complement, entregaPostal.complement) &&
        Objects.equals(this.codiPostal, entregaPostal.codiPostal) &&
        Objects.equals(this.poblacio, entregaPostal.poblacio) &&
        Objects.equals(this.municipiCodi, entregaPostal.municipiCodi) &&
        Objects.equals(this.provincia, entregaPostal.provincia) &&
        Objects.equals(this.paisCodi, entregaPostal.paisCodi) &&
        Objects.equals(this.linea1, entregaPostal.linea1) &&
        Objects.equals(this.linea2, entregaPostal.linea2) &&
        Objects.equals(this.cie, entregaPostal.cie) &&
        Objects.equals(this.formatSobre, entregaPostal.formatSobre) &&
        Objects.equals(this.formatFulla, entregaPostal.formatFulla);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipus, viaTipus, viaNom, numeroCasa, numeroQualificador, puntKm, apartatCorreus, portal, escala, planta, porta, bloc, complement, codiPostal, poblacio, municipiCodi, provincia, paisCodi, linea1, linea2, cie, formatSobre, formatFulla);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntregaPostal {\n");
    
    sb.append("    tipus: ").append(toIndentedString(tipus)).append("\n");
    sb.append("    viaTipus: ").append(toIndentedString(viaTipus)).append("\n");
    sb.append("    viaNom: ").append(toIndentedString(viaNom)).append("\n");
    sb.append("    numeroCasa: ").append(toIndentedString(numeroCasa)).append("\n");
    sb.append("    numeroQualificador: ").append(toIndentedString(numeroQualificador)).append("\n");
    sb.append("    puntKm: ").append(toIndentedString(puntKm)).append("\n");
    sb.append("    apartatCorreus: ").append(toIndentedString(apartatCorreus)).append("\n");
    sb.append("    portal: ").append(toIndentedString(portal)).append("\n");
    sb.append("    escala: ").append(toIndentedString(escala)).append("\n");
    sb.append("    planta: ").append(toIndentedString(planta)).append("\n");
    sb.append("    porta: ").append(toIndentedString(porta)).append("\n");
    sb.append("    bloc: ").append(toIndentedString(bloc)).append("\n");
    sb.append("    complement: ").append(toIndentedString(complement)).append("\n");
    sb.append("    codiPostal: ").append(toIndentedString(codiPostal)).append("\n");
    sb.append("    poblacio: ").append(toIndentedString(poblacio)).append("\n");
    sb.append("    municipiCodi: ").append(toIndentedString(municipiCodi)).append("\n");
    sb.append("    provincia: ").append(toIndentedString(provincia)).append("\n");
    sb.append("    paisCodi: ").append(toIndentedString(paisCodi)).append("\n");
    sb.append("    linea1: ").append(toIndentedString(linea1)).append("\n");
    sb.append("    linea2: ").append(toIndentedString(linea2)).append("\n");
    sb.append("    cie: ").append(toIndentedString(cie)).append("\n");
    sb.append("    formatSobre: ").append(toIndentedString(formatSobre)).append("\n");
    sb.append("    formatFulla: ").append(toIndentedString(formatFulla)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
