/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Referències (identificadors) úniques que s&#39;han assignat a de cada un dels enviaments de la notificació
 */
@JsonPropertyOrder({
  EnviamentReferenciaV2.JSON_PROPERTY_TITULAR_NOM,
  EnviamentReferenciaV2.JSON_PROPERTY_TITULAR_NIF,
  EnviamentReferenciaV2.JSON_PROPERTY_TITULAR_EMAIL,
  EnviamentReferenciaV2.JSON_PROPERTY_REFERENCIA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EnviamentReferenciaV2 {
  public static final String JSON_PROPERTY_TITULAR_NOM = "titularNom";
  private String titularNom;

  public static final String JSON_PROPERTY_TITULAR_NIF = "titularNif";
  private String titularNif;

  public static final String JSON_PROPERTY_TITULAR_EMAIL = "titularEmail";
  private String titularEmail;

  public static final String JSON_PROPERTY_REFERENCIA = "referencia";
  private String referencia;

  public EnviamentReferenciaV2() {
  }

  public EnviamentReferenciaV2 titularNom(String titularNom) {
    
    this.titularNom = titularNom;
    return this;
  }

   /**
   * Nom del titular a qui va adreçat l&#39;enviament
   * @return titularNom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITULAR_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitularNom() {
    return titularNom;
  }


  @JsonProperty(JSON_PROPERTY_TITULAR_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitularNom(String titularNom) {
    this.titularNom = titularNom;
  }


  public EnviamentReferenciaV2 titularNif(String titularNif) {
    
    this.titularNif = titularNif;
    return this;
  }

   /**
   * Nif del titular a qui va adreçat l&#39;enviament
   * @return titularNif
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITULAR_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitularNif() {
    return titularNif;
  }


  @JsonProperty(JSON_PROPERTY_TITULAR_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitularNif(String titularNif) {
    this.titularNif = titularNif;
  }


  public EnviamentReferenciaV2 titularEmail(String titularEmail) {
    
    this.titularEmail = titularEmail;
    return this;
  }

   /**
   * Correu electrònic del titular a qui va adreçat l&#39;enviament
   * @return titularEmail
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITULAR_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitularEmail() {
    return titularEmail;
  }


  @JsonProperty(JSON_PROPERTY_TITULAR_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitularEmail(String titularEmail) {
    this.titularEmail = titularEmail;
  }


  public EnviamentReferenciaV2 referencia(String referencia) {
    
    this.referencia = referencia;
    return this;
  }

   /**
   * Referència (identificador) única de l&#39;enviament a Notib
   * @return referencia
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferencia() {
    return referencia;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferencia(String referencia) {
    this.referencia = referencia;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnviamentReferenciaV2 enviamentReferenciaV2 = (EnviamentReferenciaV2) o;
    return Objects.equals(this.titularNom, enviamentReferenciaV2.titularNom) &&
        Objects.equals(this.titularNif, enviamentReferenciaV2.titularNif) &&
        Objects.equals(this.titularEmail, enviamentReferenciaV2.titularEmail) &&
        Objects.equals(this.referencia, enviamentReferenciaV2.referencia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(titularNom, titularNif, titularEmail, referencia);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnviamentReferenciaV2 {\n");
    sb.append("    titularNom: ").append(toIndentedString(titularNom)).append("\n");
    sb.append("    titularNif: ").append(toIndentedString(titularNif)).append("\n");
    sb.append("    titularEmail: ").append(toIndentedString(titularEmail)).append("\n");
    sb.append("    referencia: ").append(toIndentedString(referencia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

