/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Fitxer del justificant
 */
@Schema(description = "Fitxer del justificant")


public class Fitxer {
  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("contentType")
  private String contentType = null;

  @JsonProperty("contingut")
  private String contingut = null;

  @JsonProperty("tamany")
  private Long tamany = null;

  public Fitxer nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom del fitxer
   * @return nom
  **/
  @Schema(example = "document", description = "Nom del fitxer")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public Fitxer contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Tipus de contingut del fitxer
   * @return contentType
  **/
  @Schema(example = "application/pdf", description = "Tipus de contingut del fitxer")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public Fitxer contingut(String contingut) {
    this.contingut = contingut;
    return this;
  }

   /**
   * Contingut del fitxer
   * @return contingut
  **/
  @Schema(description = "Contingut del fitxer")
  public String getContingut() {
    return contingut;
  }

  public void setContingut(String contingut) {
    this.contingut = contingut;
  }

  public Fitxer tamany(Long tamany) {
    this.tamany = tamany;
    return this;
  }

   /**
   * Mida del fitxer
   * @return tamany
  **/
  @Schema(example = "4265384", description = "Mida del fitxer")
  public Long getTamany() {
    return tamany;
  }

  public void setTamany(Long tamany) {
    this.tamany = tamany;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fitxer fitxer = (Fitxer) o;
    return Objects.equals(this.nom, fitxer.nom) &&
        Objects.equals(this.contentType, fitxer.contentType) &&
        Objects.equals(this.contingut, fitxer.contingut) &&
        Objects.equals(this.tamany, fitxer.tamany);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nom, contentType, contingut, tamany);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fitxer {\n");
    
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    contingut: ").append(toIndentedString(contingut)).append("\n");
    sb.append("    tamany: ").append(toIndentedString(tamany)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
