/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Fitxer del justificant
 */
@JsonPropertyOrder({
  Fitxer.JSON_PROPERTY_NOM,
  Fitxer.JSON_PROPERTY_CONTENT_TYPE,
  Fitxer.JSON_PROPERTY_CONTINGUT,
  Fitxer.JSON_PROPERTY_TAMANY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Fitxer {
  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_CONTENT_TYPE = "contentType";
  private String contentType;

  public static final String JSON_PROPERTY_CONTINGUT = "contingut";
  private String contingut;

  public static final String JSON_PROPERTY_TAMANY = "tamany";
  private Long tamany;

  public Fitxer() {
  }

  public Fitxer nom(String nom) {
    
    this.nom = nom;
    return this;
  }

   /**
   * Nom del fitxer
   * @return nom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public Fitxer contentType(String contentType) {
    
    this.contentType = contentType;
    return this;
  }

   /**
   * Tipus de contingut del fitxer
   * @return contentType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContentType() {
    return contentType;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  public Fitxer contingut(String contingut) {
    
    this.contingut = contingut;
    return this;
  }

   /**
   * Contingut del fitxer
   * @return contingut
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTINGUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContingut() {
    return contingut;
  }


  @JsonProperty(JSON_PROPERTY_CONTINGUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContingut(String contingut) {
    this.contingut = contingut;
  }


  public Fitxer tamany(Long tamany) {
    
    this.tamany = tamany;
    return this;
  }

   /**
   * Mida del fitxer
   * @return tamany
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAMANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTamany() {
    return tamany;
  }


  @JsonProperty(JSON_PROPERTY_TAMANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTamany(Long tamany) {
    this.tamany = tamany;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fitxer fitxer = (Fitxer) o;
    return Objects.equals(this.nom, fitxer.nom) &&
        Objects.equals(this.contentType, fitxer.contentType) &&
        Objects.equals(this.contingut, fitxer.contingut) &&
        Objects.equals(this.tamany, fitxer.tamany);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nom, contentType, contingut, tamany);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fitxer {\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    contingut: ").append(toIndentedString(contingut)).append("\n");
    sb.append("    tamany: ").append(toIndentedString(tamany)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

