/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Tipus d&#39;interessat
 */
@JsonPropertyOrder({
  GenericInfo.JSON_PROPERTY_CODI,
  GenericInfo.JSON_PROPERTY_NOM,
  GenericInfo.JSON_PROPERTY_DESCRIPCIO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GenericInfo {
  public static final String JSON_PROPERTY_CODI = "codi";
  private String codi;

  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_DESCRIPCIO = "descripcio";
  private String descripcio;

  public GenericInfo() {
  }

  public GenericInfo codi(String codi) {
    
    this.codi = codi;
    return this;
  }

   /**
   * Codi de l&#39;element
   * @return codi
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(JSON_PROPERTY_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodi(String codi) {
    this.codi = codi;
  }


  public GenericInfo nom(String nom) {
    
    this.nom = nom;
    return this;
  }

   /**
   * Nom de l&#39;element
   * @return nom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public GenericInfo descripcio(String descripcio) {
    
    this.descripcio = descripcio;
    return this;
  }

   /**
   * Descripcio de l&#39;element
   * @return descripcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescripcio() {
    return descripcio;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescripcio(String descripcio) {
    this.descripcio = descripcio;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericInfo genericInfo = (GenericInfo) o;
    return Objects.equals(this.codi, genericInfo.codi) &&
        Objects.equals(this.nom, genericInfo.nom) &&
        Objects.equals(this.descripcio, genericInfo.descripcio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, nom, descripcio);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericInfo {\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

