/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Tipus d&#x27;interessat
 */
@Schema(description = "Tipus d'interessat")


public class GenericInfo {
  @JsonProperty("codi")
  private String codi = null;

  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("descripcio")
  private String descripcio = null;

  public GenericInfo codi(String codi) {
    this.codi = codi;
    return this;
  }

   /**
   * Codi de l&#x27;element
   * @return codi
  **/
  @Schema(example = "codi", description = "Codi de l'element")
  public String getCodi() {
    return codi;
  }

  public void setCodi(String codi) {
    this.codi = codi;
  }

  public GenericInfo nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom de l&#x27;element
   * @return nom
  **/
  @Schema(example = "nom", description = "Nom de l'element")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public GenericInfo descripcio(String descripcio) {
    this.descripcio = descripcio;
    return this;
  }

   /**
   * Descripcio de l&#x27;element
   * @return descripcio
  **/
  @Schema(example = "descripcio", description = "Descripcio de l'element")
  public String getDescripcio() {
    return descripcio;
  }

  public void setDescripcio(String descripcio) {
    this.descripcio = descripcio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericInfo genericInfo = (GenericInfo) o;
    return Objects.equals(this.codi, genericInfo.codi) &&
        Objects.equals(this.nom, genericInfo.nom) &&
        Objects.equals(this.descripcio, genericInfo.descripcio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, nom, descripcio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericInfo {\n");
    
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
