/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Objecte amb les dades necessàries per donar el permís
 */
@JsonPropertyOrder({
  PermisConsulta.JSON_PROPERTY_CODI_DIR3_ENTITAT,
  PermisConsulta.JSON_PROPERTY_PERMIS_CONSULTA,
  PermisConsulta.JSON_PROPERTY_PROCEDIMENT_CODI,
  PermisConsulta.JSON_PROPERTY_USUARI_CODI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PermisConsulta {
  public static final String JSON_PROPERTY_CODI_DIR3_ENTITAT = "codiDir3Entitat";
  private String codiDir3Entitat;

  public static final String JSON_PROPERTY_PERMIS_CONSULTA = "permisConsulta";
  private Boolean permisConsulta;

  public static final String JSON_PROPERTY_PROCEDIMENT_CODI = "procedimentCodi";
  private String procedimentCodi;

  public static final String JSON_PROPERTY_USUARI_CODI = "usuariCodi";
  private String usuariCodi;

  public PermisConsulta() {
  }

  public PermisConsulta codiDir3Entitat(String codiDir3Entitat) {
    
    this.codiDir3Entitat = codiDir3Entitat;
    return this;
  }

   /**
   * Codi dir3 de l&#39;entitat en la que es vol donar permís de consulta
   * @return codiDir3Entitat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODI_DIR3_ENTITAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodiDir3Entitat() {
    return codiDir3Entitat;
  }


  @JsonProperty(JSON_PROPERTY_CODI_DIR3_ENTITAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodiDir3Entitat(String codiDir3Entitat) {
    this.codiDir3Entitat = codiDir3Entitat;
  }


  public PermisConsulta permisConsulta(Boolean permisConsulta) {
    
    this.permisConsulta = permisConsulta;
    return this;
  }

   /**
   * Indica si es vol donar o treure el permís de consulta
   * @return permisConsulta
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMIS_CONSULTA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isPermisConsulta() {
    return permisConsulta;
  }


  @JsonProperty(JSON_PROPERTY_PERMIS_CONSULTA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermisConsulta(Boolean permisConsulta) {
    this.permisConsulta = permisConsulta;
  }


  public PermisConsulta procedimentCodi(String procedimentCodi) {
    
    this.procedimentCodi = procedimentCodi;
    return this;
  }

   /**
   * Codi SIA del procediment sobre el que es vol donar permís de consulta
   * @return procedimentCodi
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCEDIMENT_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcedimentCodi() {
    return procedimentCodi;
  }


  @JsonProperty(JSON_PROPERTY_PROCEDIMENT_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcedimentCodi(String procedimentCodi) {
    this.procedimentCodi = procedimentCodi;
  }


  public PermisConsulta usuariCodi(String usuariCodi) {
    
    this.usuariCodi = usuariCodi;
    return this;
  }

   /**
   * Codi de l&#39;usuari al que es vol donar permís de consulta
   * @return usuariCodi
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USUARI_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsuariCodi() {
    return usuariCodi;
  }


  @JsonProperty(JSON_PROPERTY_USUARI_CODI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsuariCodi(String usuariCodi) {
    this.usuariCodi = usuariCodi;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermisConsulta permisConsulta = (PermisConsulta) o;
    return Objects.equals(this.codiDir3Entitat, permisConsulta.codiDir3Entitat) &&
        Objects.equals(this.permisConsulta, permisConsulta.permisConsulta) &&
        Objects.equals(this.procedimentCodi, permisConsulta.procedimentCodi) &&
        Objects.equals(this.usuariCodi, permisConsulta.usuariCodi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiDir3Entitat, permisConsulta, procedimentCodi, usuariCodi);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermisConsulta {\n");
    sb.append("    codiDir3Entitat: ").append(toIndentedString(codiDir3Entitat)).append("\n");
    sb.append("    permisConsulta: ").append(toIndentedString(permisConsulta)).append("\n");
    sb.append("    procedimentCodi: ").append(toIndentedString(procedimentCodi)).append("\n");
    sb.append("    usuariCodi: ").append(toIndentedString(usuariCodi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

