/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.GenericInfo;
/**
 * Persones representans, destinatàries de l&#x27;enviament
 */
@Schema(description = "Persones representans, destinatàries de l'enviament")


public class PersonaConsultaV2 {
  @JsonProperty("tipus")
  private GenericInfo tipus = null;

  @JsonProperty("nom")
  private String nom = null;

  @JsonProperty("llinatge1")
  private String llinatge1 = null;

  @JsonProperty("llinatge2")
  private String llinatge2 = null;

  @JsonProperty("nif")
  private String nif = null;

  @JsonProperty("email")
  private String email = null;

  public PersonaConsultaV2 tipus(GenericInfo tipus) {
    this.tipus = tipus;
    return this;
  }

   /**
   * Get tipus
   * @return tipus
  **/
  @Schema(description = "")
  public GenericInfo getTipus() {
    return tipus;
  }

  public void setTipus(GenericInfo tipus) {
    this.tipus = tipus;
  }

  public PersonaConsultaV2 nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom de la persona
   * @return nom
  **/
  @Schema(example = "codi", description = "Nom de la persona")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }

  public PersonaConsultaV2 llinatge1(String llinatge1) {
    this.llinatge1 = llinatge1;
    return this;
  }

   /**
   * Primer llinatge de la persona
   * @return llinatge1
  **/
  @Schema(example = "codi", description = "Primer llinatge de la persona")
  public String getLlinatge1() {
    return llinatge1;
  }

  public void setLlinatge1(String llinatge1) {
    this.llinatge1 = llinatge1;
  }

  public PersonaConsultaV2 llinatge2(String llinatge2) {
    this.llinatge2 = llinatge2;
    return this;
  }

   /**
   * Segon llinatge de la persona
   * @return llinatge2
  **/
  @Schema(example = "codi", description = "Segon llinatge de la persona")
  public String getLlinatge2() {
    return llinatge2;
  }

  public void setLlinatge2(String llinatge2) {
    this.llinatge2 = llinatge2;
  }

  public PersonaConsultaV2 nif(String nif) {
    this.nif = nif;
    return this;
  }

   /**
   * NIF de la persona
   * @return nif
  **/
  @Schema(example = "codi", description = "NIF de la persona")
  public String getNif() {
    return nif;
  }

  public void setNif(String nif) {
    this.nif = nif;
  }

  public PersonaConsultaV2 email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Correu electrònic de la persona
   * @return email
  **/
  @Schema(example = "codi", description = "Correu electrònic de la persona")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonaConsultaV2 personaConsultaV2 = (PersonaConsultaV2) o;
    return Objects.equals(this.tipus, personaConsultaV2.tipus) &&
        Objects.equals(this.nom, personaConsultaV2.nom) &&
        Objects.equals(this.llinatge1, personaConsultaV2.llinatge1) &&
        Objects.equals(this.llinatge2, personaConsultaV2.llinatge2) &&
        Objects.equals(this.nif, personaConsultaV2.nif) &&
        Objects.equals(this.email, personaConsultaV2.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipus, nom, llinatge1, llinatge2, nif, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonaConsultaV2 {\n");
    
    sb.append("    tipus: ").append(toIndentedString(tipus)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    llinatge1: ").append(toIndentedString(llinatge1)).append("\n");
    sb.append("    llinatge2: ").append(toIndentedString(llinatge2)).append("\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
