/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.GenericInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Persones representans, destinatàries de l&#39;enviament
 */
@JsonPropertyOrder({
  PersonaConsultaV2.JSON_PROPERTY_TIPUS,
  PersonaConsultaV2.JSON_PROPERTY_NOM,
  PersonaConsultaV2.JSON_PROPERTY_LLINATGE1,
  PersonaConsultaV2.JSON_PROPERTY_LLINATGE2,
  PersonaConsultaV2.JSON_PROPERTY_NIF,
  PersonaConsultaV2.JSON_PROPERTY_EMAIL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PersonaConsultaV2 {
  public static final String JSON_PROPERTY_TIPUS = "tipus";
  private GenericInfo tipus;

  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_LLINATGE1 = "llinatge1";
  private String llinatge1;

  public static final String JSON_PROPERTY_LLINATGE2 = "llinatge2";
  private String llinatge2;

  public static final String JSON_PROPERTY_NIF = "nif";
  private String nif;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public PersonaConsultaV2() {
  }

  public PersonaConsultaV2 tipus(GenericInfo tipus) {
    
    this.tipus = tipus;
    return this;
  }

   /**
   * Get tipus
   * @return tipus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIPUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GenericInfo getTipus() {
    return tipus;
  }


  @JsonProperty(JSON_PROPERTY_TIPUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTipus(GenericInfo tipus) {
    this.tipus = tipus;
  }


  public PersonaConsultaV2 nom(String nom) {
    
    this.nom = nom;
    return this;
  }

   /**
   * Nom de la persona
   * @return nom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public PersonaConsultaV2 llinatge1(String llinatge1) {
    
    this.llinatge1 = llinatge1;
    return this;
  }

   /**
   * Primer llinatge de la persona
   * @return llinatge1
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LLINATGE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLlinatge1() {
    return llinatge1;
  }


  @JsonProperty(JSON_PROPERTY_LLINATGE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLlinatge1(String llinatge1) {
    this.llinatge1 = llinatge1;
  }


  public PersonaConsultaV2 llinatge2(String llinatge2) {
    
    this.llinatge2 = llinatge2;
    return this;
  }

   /**
   * Segon llinatge de la persona
   * @return llinatge2
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LLINATGE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLlinatge2() {
    return llinatge2;
  }


  @JsonProperty(JSON_PROPERTY_LLINATGE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLlinatge2(String llinatge2) {
    this.llinatge2 = llinatge2;
  }


  public PersonaConsultaV2 nif(String nif) {
    
    this.nif = nif;
    return this;
  }

   /**
   * NIF de la persona
   * @return nif
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNif() {
    return nif;
  }


  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNif(String nif) {
    this.nif = nif;
  }


  public PersonaConsultaV2 email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Correu electrònic de la persona
   * @return email
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonaConsultaV2 personaConsultaV2 = (PersonaConsultaV2) o;
    return Objects.equals(this.tipus, personaConsultaV2.tipus) &&
        Objects.equals(this.nom, personaConsultaV2.nom) &&
        Objects.equals(this.llinatge1, personaConsultaV2.llinatge1) &&
        Objects.equals(this.llinatge2, personaConsultaV2.llinatge2) &&
        Objects.equals(this.nif, personaConsultaV2.nif) &&
        Objects.equals(this.email, personaConsultaV2.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipus, nom, llinatge1, llinatge2, nif, email);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonaConsultaV2 {\n");
    sb.append("    tipus: ").append(toIndentedString(tipus)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    llinatge1: ").append(toIndentedString(llinatge1)).append("\n");
    sb.append("    llinatge2: ").append(toIndentedString(llinatge2)).append("\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

