/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Representants a qui enviar l&#39;enviament
 */
@JsonPropertyOrder({
  Persona.JSON_PROPERTY_INCAPACITAT,
  Persona.JSON_PROPERTY_INTERESSAT_TIPUS,
  Persona.JSON_PROPERTY_NOM,
  Persona.JSON_PROPERTY_LLINATGE1,
  Persona.JSON_PROPERTY_LLINATGE2,
  Persona.JSON_PROPERTY_DOCUMENT_TIPUS,
  Persona.JSON_PROPERTY_NIF,
  Persona.JSON_PROPERTY_TELEFON,
  Persona.JSON_PROPERTY_EMAIL,
  Persona.JSON_PROPERTY_RAO_SOCIAL,
  Persona.JSON_PROPERTY_DIR3_CODI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Persona {
  public static final String JSON_PROPERTY_INCAPACITAT = "incapacitat";
  private Boolean incapacitat = false;

  /**
   * Enumerat que indica el tipus de l’interessat que realitza l’enviament.  * En cas d&#39;indicar un interessat tipus FISICA_SENSE_NIF serà obligatori informar el camp documentTipus
   */
  public enum InteressatTipusEnum {
    ADMINISTRACIO("ADMINISTRACIO"),
    
    FISICA("FISICA"),
    
    JURIDICA("JURIDICA"),
    
    FISICA_SENSE_NIF("FISICA_SENSE_NIF");

    private String value;

    InteressatTipusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InteressatTipusEnum fromValue(String value) {
      for (InteressatTipusEnum b : InteressatTipusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INTERESSAT_TIPUS = "interessatTipus";
  private InteressatTipusEnum interessatTipus;

  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public static final String JSON_PROPERTY_LLINATGE1 = "llinatge1";
  private String llinatge1;

  public static final String JSON_PROPERTY_LLINATGE2 = "llinatge2";
  private String llinatge2;

  /**
   * Enumerat que indica el tipus de document aportat per l’interessat  * Aquest camp únicament es té en compte quan el tipus d’interessat és FISICA_SENSE_NIF
   */
  public enum DocumentTipusEnum {
    PASSAPORT("PASSAPORT"),
    
    ESTRANGER("ESTRANGER"),
    
    ALTRE("ALTRE");

    private String value;

    DocumentTipusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DocumentTipusEnum fromValue(String value) {
      for (DocumentTipusEnum b : DocumentTipusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DOCUMENT_TIPUS = "documentTipus";
  private DocumentTipusEnum documentTipus;

  public static final String JSON_PROPERTY_NIF = "nif";
  private String nif;

  public static final String JSON_PROPERTY_TELEFON = "telefon";
  private String telefon;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_RAO_SOCIAL = "raoSocial";
  private String raoSocial;

  public static final String JSON_PROPERTY_DIR3_CODI = "dir3Codi";
  private String dir3Codi;

  public Persona() {
  }

  public Persona incapacitat(Boolean incapacitat) {
    
    this.incapacitat = incapacitat;
    return this;
  }

   /**
   * Indica si el titular es incapacitat per llegir/rebutjar la notificació. En aquest cas, seria obligatori informar un destinatari de l&#39;enviament.
   * @return incapacitat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INCAPACITAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isIncapacitat() {
    return incapacitat;
  }


  @JsonProperty(JSON_PROPERTY_INCAPACITAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncapacitat(Boolean incapacitat) {
    this.incapacitat = incapacitat;
  }


  public Persona interessatTipus(InteressatTipusEnum interessatTipus) {
    
    this.interessatTipus = interessatTipus;
    return this;
  }

   /**
   * Enumerat que indica el tipus de l’interessat que realitza l’enviament.  * En cas d&#39;indicar un interessat tipus FISICA_SENSE_NIF serà obligatori informar el camp documentTipus
   * @return interessatTipus
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INTERESSAT_TIPUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public InteressatTipusEnum getInteressatTipus() {
    return interessatTipus;
  }


  @JsonProperty(JSON_PROPERTY_INTERESSAT_TIPUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInteressatTipus(InteressatTipusEnum interessatTipus) {
    this.interessatTipus = interessatTipus;
  }


  public Persona nom(String nom) {
    
    this.nom = nom;
    return this;
  }

   /**
   * Nom del titular.  * Obligatori en cas de persones físiques  * Mida màxima de 255 caràcters quan es tracta d&#39;una administració  * Mida màxima de 30 caràcters per la resta de tipus d&#39;interessats  * En el cas de persones jurídiques es posarà el nom en el camp raoSocial. En cas de no informar-se el camp raoSocial s&#39;agafarà el valor indicat en aquest camp
   * @return nom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }


  public Persona llinatge1(String llinatge1) {
    
    this.llinatge1 = llinatge1;
    return this;
  }

   /**
   * Primer llinatge de l’interessat  * Obligatori en cas de persones físiques
   * @return llinatge1
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LLINATGE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLlinatge1() {
    return llinatge1;
  }


  @JsonProperty(JSON_PROPERTY_LLINATGE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLlinatge1(String llinatge1) {
    this.llinatge1 = llinatge1;
  }


  public Persona llinatge2(String llinatge2) {
    
    this.llinatge2 = llinatge2;
    return this;
  }

   /**
   * Segon llinatge de l’interessat
   * @return llinatge2
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LLINATGE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLlinatge2() {
    return llinatge2;
  }


  @JsonProperty(JSON_PROPERTY_LLINATGE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLlinatge2(String llinatge2) {
    this.llinatge2 = llinatge2;
  }


  public Persona documentTipus(DocumentTipusEnum documentTipus) {
    
    this.documentTipus = documentTipus;
    return this;
  }

   /**
   * Enumerat que indica el tipus de document aportat per l’interessat  * Aquest camp únicament es té en compte quan el tipus d’interessat és FISICA_SENSE_NIF
   * @return documentTipus
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_TIPUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DocumentTipusEnum getDocumentTipus() {
    return documentTipus;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_TIPUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentTipus(DocumentTipusEnum documentTipus) {
    this.documentTipus = documentTipus;
  }


  public Persona nif(String nif) {
    
    this.nif = nif;
    return this;
  }

   /**
   * Número del document de l&#39;interessat  * Obligatori excepte per interessats tipus FISICA_SENSE_NIF
   * @return nif
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNif() {
    return nif;
  }


  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNif(String nif) {
    this.nif = nif;
  }


  public Persona telefon(String telefon) {
    
    this.telefon = telefon;
    return this;
  }

   /**
   * Telèfon de l’interessat  * Actualment no s’utilitza
   * @return telefon
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TELEFON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTelefon() {
    return telefon;
  }


  @JsonProperty(JSON_PROPERTY_TELEFON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTelefon(String telefon) {
    this.telefon = telefon;
  }


  public Persona email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Correu electrònic de l’interessat.   * Altament recomanat el seu ús.
   * @return email
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }


  public Persona raoSocial(String raoSocial) {
    
    this.raoSocial = raoSocial;
    return this;
  }

   /**
   * Raó social de l’interessat  * S’utilitza únicament en cas de persones jurídiques, i si no s’informa aquest camp, s’utilitzarà el valor del camp nom. És obligatori que un dels dos camps estigui informat
   * @return raoSocial
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RAO_SOCIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRaoSocial() {
    return raoSocial;
  }


  @JsonProperty(JSON_PROPERTY_RAO_SOCIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRaoSocial(String raoSocial) {
    this.raoSocial = raoSocial;
  }


  public Persona dir3Codi(String dir3Codi) {
    
    this.dir3Codi = dir3Codi;
    return this;
  }

   /**
   * Codi DIR3 de la administració a la que pertany la persona.  * Obligatori si s’ha d’enviar a una administració.
   * @return dir3Codi
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DIR3_CODI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDir3Codi() {
    return dir3Codi;
  }


  @JsonProperty(JSON_PROPERTY_DIR3_CODI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDir3Codi(String dir3Codi) {
    this.dir3Codi = dir3Codi;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Persona persona = (Persona) o;
    return Objects.equals(this.incapacitat, persona.incapacitat) &&
        Objects.equals(this.interessatTipus, persona.interessatTipus) &&
        Objects.equals(this.nom, persona.nom) &&
        Objects.equals(this.llinatge1, persona.llinatge1) &&
        Objects.equals(this.llinatge2, persona.llinatge2) &&
        Objects.equals(this.documentTipus, persona.documentTipus) &&
        Objects.equals(this.nif, persona.nif) &&
        Objects.equals(this.telefon, persona.telefon) &&
        Objects.equals(this.email, persona.email) &&
        Objects.equals(this.raoSocial, persona.raoSocial) &&
        Objects.equals(this.dir3Codi, persona.dir3Codi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(incapacitat, interessatTipus, nom, llinatge1, llinatge2, documentTipus, nif, telefon, email, raoSocial, dir3Codi);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Persona {\n");
    sb.append("    incapacitat: ").append(toIndentedString(incapacitat)).append("\n");
    sb.append("    interessatTipus: ").append(toIndentedString(interessatTipus)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    llinatge1: ").append(toIndentedString(llinatge1)).append("\n");
    sb.append("    llinatge2: ").append(toIndentedString(llinatge2)).append("\n");
    sb.append("    documentTipus: ").append(toIndentedString(documentTipus)).append("\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    telefon: ").append(toIndentedString(telefon)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    raoSocial: ").append(toIndentedString(raoSocial)).append("\n");
    sb.append("    dir3Codi: ").append(toIndentedString(dir3Codi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

