/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Procediment al que pertany la notificació
 */
@JsonPropertyOrder({
  Procediment.JSON_PROPERTY_CODI_SIA,
  Procediment.JSON_PROPERTY_NOM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Procediment {
  public static final String JSON_PROPERTY_CODI_SIA = "codiSia";
  private String codiSia;

  public static final String JSON_PROPERTY_NOM = "nom";
  private String nom;

  public Procediment() {
  }

  public Procediment codiSia(String codiSia) {
    
    this.codiSia = codiSia;
    return this;
  }

   /**
   * Codi SIA del procediment
   * @return codiSia
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODI_SIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodiSia() {
    return codiSia;
  }


  @JsonProperty(JSON_PROPERTY_CODI_SIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodiSia(String codiSia) {
    this.codiSia = codiSia;
  }


  public Procediment nom(String nom) {
    
    this.nom = nom;
    return this;
  }

   /**
   * Nom del procediment
   * @return nom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(JSON_PROPERTY_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(String nom) {
    this.nom = nom;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Procediment procediment = (Procediment) o;
    return Objects.equals(this.codiSia, procediment.codiSia) &&
        Objects.equals(this.nom, procediment.nom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiSia, nom);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Procediment {\n");
    sb.append("    codiSia: ").append(toIndentedString(codiSia)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

