/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Procediment al que pertany la notificació
 */
@Schema(description = "Procediment al que pertany la notificació")


public class Procediment {
  @JsonProperty("codiSia")
  private String codiSia = null;

  @JsonProperty("nom")
  private String nom = null;

  public Procediment codiSia(String codiSia) {
    this.codiSia = codiSia;
    return this;
  }

   /**
   * Codi SIA del procediment
   * @return codiSia
  **/
  @Schema(example = "666666", description = "Codi SIA del procediment")
  public String getCodiSia() {
    return codiSia;
  }

  public void setCodiSia(String codiSia) {
    this.codiSia = codiSia;
  }

  public Procediment nom(String nom) {
    this.nom = nom;
    return this;
  }

   /**
   * Nom del procediment
   * @return nom
  **/
  @Schema(example = "Instància genèrica", description = "Nom del procediment")
  public String getNom() {
    return nom;
  }

  public void setNom(String nom) {
    this.nom = nom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Procediment procediment = (Procediment) o;
    return Objects.equals(this.codiSia, procediment.codiSia) &&
        Objects.equals(this.nom, procediment.nom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiSia, nom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Procediment {\n");
    
    sb.append("    codiSia: ").append(toIndentedString(codiSia)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
