/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Informació de l&#x27;apunt de registre de sortida realitzat per l&#x27;enviament
 */
@Schema(description = "Informació de l'apunt de registre de sortida realitzat per l'enviament")


public class Registre {
  @JsonProperty("numero")
  private Integer numero = null;

  @JsonProperty("data")
  private Long data = null;

  @JsonProperty("numeroFormatat")
  private String numeroFormatat = null;

  /**
   * Estat del registre
   */
  public enum EstatEnum {
    VALID("VALID"),
    RESERVA("RESERVA"),
    PENDENT("PENDENT"),
    OFICI_EXTERN("OFICI_EXTERN"),
    OFICI_INTERN("OFICI_INTERN"),
    OFICI_ACCEPTAT("OFICI_ACCEPTAT"),
    DISTRIBUIT("DISTRIBUIT"),
    ANULAT("ANULAT"),
    RECTIFICAT("RECTIFICAT"),
    REBUTJAT("REBUTJAT"),
    REENVIAT("REENVIAT"),
    DISTRIBUINT("DISTRIBUINT"),
    OFICI_SIR("OFICI_SIR");

    private String value;

    EstatEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static EstatEnum fromValue(String input) {
      for (EstatEnum b : EstatEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("estat")
  private EstatEnum estat = null;

  @JsonProperty("oficina")
  private String oficina = null;

  @JsonProperty("llibre")
  private String llibre = null;

  public Registre numero(Integer numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Número de registre
   * @return numero
  **/
  @Schema(example = "1753", description = "Número de registre")
  public Integer getNumero() {
    return numero;
  }

  public void setNumero(Integer numero) {
    this.numero = numero;
  }

  public Registre data(Long data) {
    this.data = data;
    return this;
  }

   /**
   * Data del registre
   * @return data
  **/
  @Schema(example = "1706168093962", description = "Data del registre")
  public Long getData() {
    return data;
  }

  public void setData(Long data) {
    this.data = data;
  }

  public Registre numeroFormatat(String numeroFormatat) {
    this.numeroFormatat = numeroFormatat;
    return this;
  }

   /**
   * Número de registre amb format
   * @return numeroFormatat
  **/
  @Schema(example = "GOIBS1753/2023", description = "Número de registre amb format")
  public String getNumeroFormatat() {
    return numeroFormatat;
  }

  public void setNumeroFormatat(String numeroFormatat) {
    this.numeroFormatat = numeroFormatat;
  }

  public Registre estat(EstatEnum estat) {
    this.estat = estat;
    return this;
  }

   /**
   * Estat del registre
   * @return estat
  **/
  @Schema(example = "VALID", description = "Estat del registre")
  public EstatEnum getEstat() {
    return estat;
  }

  public void setEstat(EstatEnum estat) {
    this.estat = estat;
  }

  public Registre oficina(String oficina) {
    this.oficina = oficina;
    return this;
  }

   /**
   * Oficina on s&#x27;ha realitzat el registre
   * @return oficina
  **/
  @Schema(example = "Oficina Virtual", description = "Oficina on s'ha realitzat el registre")
  public String getOficina() {
    return oficina;
  }

  public void setOficina(String oficina) {
    this.oficina = oficina;
  }

  public Registre llibre(String llibre) {
    this.llibre = llibre;
    return this;
  }

   /**
   * Llibre on s&#x27;ha anotat el registre
   * @return llibre
  **/
  @Schema(example = "Govern de les Illes Balears", description = "Llibre on s'ha anotat el registre")
  public String getLlibre() {
    return llibre;
  }

  public void setLlibre(String llibre) {
    this.llibre = llibre;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Registre registre = (Registre) o;
    return Objects.equals(this.numero, registre.numero) &&
        Objects.equals(this.data, registre.data) &&
        Objects.equals(this.numeroFormatat, registre.numeroFormatat) &&
        Objects.equals(this.estat, registre.estat) &&
        Objects.equals(this.oficina, registre.oficina) &&
        Objects.equals(this.llibre, registre.llibre);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numero, data, numeroFormatat, estat, oficina, llibre);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Registre {\n");
    
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    numeroFormatat: ").append(toIndentedString(numeroFormatat)).append("\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    oficina: ").append(toIndentedString(oficina)).append("\n");
    sb.append("    llibre: ").append(toIndentedString(llibre)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
