/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.TransmissioV2;
/**
 * RespostaConsultaV2
 */



public class RespostaConsultaV2 {
  @JsonProperty("numeroElementsTotals")
  private Integer numeroElementsTotals = null;

  @JsonProperty("numeroElementsRetornats")
  private Integer numeroElementsRetornats = null;

  @JsonProperty("resultat")
  private List<TransmissioV2> resultat = null;

  @JsonProperty("error")
  private Boolean error = null;

  @JsonProperty("errorDescripcio")
  private String errorDescripcio = null;

  @JsonProperty("errorData")
  private Long errorData = null;

  public RespostaConsultaV2 numeroElementsTotals(Integer numeroElementsTotals) {
    this.numeroElementsTotals = numeroElementsTotals;
    return this;
  }

   /**
   * Número total de notificacions, segons el filtre aplicat
   * @return numeroElementsTotals
  **/
  @Schema(example = "127", description = "Número total de notificacions, segons el filtre aplicat")
  public Integer getNumeroElementsTotals() {
    return numeroElementsTotals;
  }

  public void setNumeroElementsTotals(Integer numeroElementsTotals) {
    this.numeroElementsTotals = numeroElementsTotals;
  }

  public RespostaConsultaV2 numeroElementsRetornats(Integer numeroElementsRetornats) {
    this.numeroElementsRetornats = numeroElementsRetornats;
    return this;
  }

   /**
   * Número de notificacions retornades, depenent de la paginació
   * @return numeroElementsRetornats
  **/
  @Schema(example = "10", description = "Número de notificacions retornades, depenent de la paginació")
  public Integer getNumeroElementsRetornats() {
    return numeroElementsRetornats;
  }

  public void setNumeroElementsRetornats(Integer numeroElementsRetornats) {
    this.numeroElementsRetornats = numeroElementsRetornats;
  }

  public RespostaConsultaV2 resultat(List<TransmissioV2> resultat) {
    this.resultat = resultat;
    return this;
  }

  public RespostaConsultaV2 addResultatItem(TransmissioV2 resultatItem) {
    if (this.resultat == null) {
      this.resultat = new ArrayList<TransmissioV2>();
    }
    this.resultat.add(resultatItem);
    return this;
  }

   /**
   * Llistat de les notificacions retornades
   * @return resultat
  **/
  @Schema(description = "Llistat de les notificacions retornades")
  public List<TransmissioV2> getResultat() {
    return resultat;
  }

  public void setResultat(List<TransmissioV2> resultat) {
    this.resultat = resultat;
  }

  public RespostaConsultaV2 error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Error en la consulta
   * @return error
  **/
  @Schema(example = "false", description = "Error en la consulta")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public RespostaConsultaV2 errorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
    return this;
  }

   /**
   * Descripció de l&#x27;error
   * @return errorDescripcio
  **/
  @Schema(example = "java.lang.NullPointerException", description = "Descripció de l'error")
  public String getErrorDescripcio() {
    return errorDescripcio;
  }

  public void setErrorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
  }

  public RespostaConsultaV2 errorData(Long errorData) {
    this.errorData = errorData;
    return this;
  }

   /**
   * Data de l&#x27;error
   * @return errorData
  **/
  @Schema(example = "1706168093962", description = "Data de l'error")
  public Long getErrorData() {
    return errorData;
  }

  public void setErrorData(Long errorData) {
    this.errorData = errorData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespostaConsultaV2 respostaConsultaV2 = (RespostaConsultaV2) o;
    return Objects.equals(this.numeroElementsTotals, respostaConsultaV2.numeroElementsTotals) &&
        Objects.equals(this.numeroElementsRetornats, respostaConsultaV2.numeroElementsRetornats) &&
        Objects.equals(this.resultat, respostaConsultaV2.resultat) &&
        Objects.equals(this.error, respostaConsultaV2.error) &&
        Objects.equals(this.errorDescripcio, respostaConsultaV2.errorDescripcio) &&
        Objects.equals(this.errorData, respostaConsultaV2.errorData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroElementsTotals, numeroElementsRetornats, resultat, error, errorDescripcio, errorData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespostaConsultaV2 {\n");
    
    sb.append("    numeroElementsTotals: ").append(toIndentedString(numeroElementsTotals)).append("\n");
    sb.append("    numeroElementsRetornats: ").append(toIndentedString(numeroElementsRetornats)).append("\n");
    sb.append("    resultat: ").append(toIndentedString(resultat)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorDescripcio: ").append(toIndentedString(errorDescripcio)).append("\n");
    sb.append("    errorData: ").append(toIndentedString(errorData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
