/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.TransmissioV2;
/**
 * RespostaConsultaV2
 */



public class RespostaConsultaV2 {
  @JsonProperty("emisor")
  private List<TransmissioV2> emisor = null;

  public RespostaConsultaV2 emisor(List<TransmissioV2> emisor) {
    this.emisor = emisor;
    return this;
  }

  public RespostaConsultaV2 addEmisorItem(TransmissioV2 emisorItem) {
    if (this.emisor == null) {
      this.emisor = new ArrayList<TransmissioV2>();
    }
    this.emisor.add(emisorItem);
    return this;
  }

   /**
   * Llistat de les notificacions retornades
   * @return emisor
  **/
  @Schema(description = "Llistat de les notificacions retornades")
  public List<TransmissioV2> getEmisor() {
    return emisor;
  }

  public void setEmisor(List<TransmissioV2> emisor) {
    this.emisor = emisor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespostaConsultaV2 respostaConsultaV2 = (RespostaConsultaV2) o;
    return Objects.equals(this.emisor, respostaConsultaV2.emisor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emisor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespostaConsultaV2 {\n");
    
    sb.append("    emisor: ").append(toIndentedString(emisor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
