/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.TransmissioV2;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RespostaConsultaV2
 */
@JsonPropertyOrder({
  RespostaConsultaV2.JSON_PROPERTY_NUMERO_ELEMENTS_TOTALS,
  RespostaConsultaV2.JSON_PROPERTY_NUMERO_ELEMENTS_RETORNATS,
  RespostaConsultaV2.JSON_PROPERTY_RESULTAT,
  RespostaConsultaV2.JSON_PROPERTY_ERROR,
  RespostaConsultaV2.JSON_PROPERTY_ERROR_DESCRIPCIO,
  RespostaConsultaV2.JSON_PROPERTY_ERROR_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RespostaConsultaV2 {
  public static final String JSON_PROPERTY_NUMERO_ELEMENTS_TOTALS = "numeroElementsTotals";
  private Integer numeroElementsTotals;

  public static final String JSON_PROPERTY_NUMERO_ELEMENTS_RETORNATS = "numeroElementsRetornats";
  private Integer numeroElementsRetornats;

  public static final String JSON_PROPERTY_RESULTAT = "resultat";
  private List<TransmissioV2> resultat;

  public static final String JSON_PROPERTY_ERROR = "error";
  private Boolean error;

  public static final String JSON_PROPERTY_ERROR_DESCRIPCIO = "errorDescripcio";
  private String errorDescripcio;

  public static final String JSON_PROPERTY_ERROR_DATA = "errorData";
  private Long errorData;

  public RespostaConsultaV2() {
  }

  public RespostaConsultaV2 numeroElementsTotals(Integer numeroElementsTotals) {
    
    this.numeroElementsTotals = numeroElementsTotals;
    return this;
  }

   /**
   * Número total de notificacions, segons el filtre aplicat
   * @return numeroElementsTotals
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMERO_ELEMENTS_TOTALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumeroElementsTotals() {
    return numeroElementsTotals;
  }


  @JsonProperty(JSON_PROPERTY_NUMERO_ELEMENTS_TOTALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumeroElementsTotals(Integer numeroElementsTotals) {
    this.numeroElementsTotals = numeroElementsTotals;
  }


  public RespostaConsultaV2 numeroElementsRetornats(Integer numeroElementsRetornats) {
    
    this.numeroElementsRetornats = numeroElementsRetornats;
    return this;
  }

   /**
   * Número de notificacions retornades, depenent de la paginació
   * @return numeroElementsRetornats
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMERO_ELEMENTS_RETORNATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumeroElementsRetornats() {
    return numeroElementsRetornats;
  }


  @JsonProperty(JSON_PROPERTY_NUMERO_ELEMENTS_RETORNATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumeroElementsRetornats(Integer numeroElementsRetornats) {
    this.numeroElementsRetornats = numeroElementsRetornats;
  }


  public RespostaConsultaV2 resultat(List<TransmissioV2> resultat) {
    
    this.resultat = resultat;
    return this;
  }

  public RespostaConsultaV2 addResultatItem(TransmissioV2 resultatItem) {
    if (this.resultat == null) {
      this.resultat = new ArrayList<>();
    }
    this.resultat.add(resultatItem);
    return this;
  }

   /**
   * Llistat de les notificacions retornades
   * @return resultat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TransmissioV2> getResultat() {
    return resultat;
  }


  @JsonProperty(JSON_PROPERTY_RESULTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultat(List<TransmissioV2> resultat) {
    this.resultat = resultat;
  }


  public RespostaConsultaV2 error(Boolean error) {
    
    this.error = error;
    return this;
  }

   /**
   * Error en la consulta
   * @return error
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(Boolean error) {
    this.error = error;
  }


  public RespostaConsultaV2 errorDescripcio(String errorDescripcio) {
    
    this.errorDescripcio = errorDescripcio;
    return this;
  }

   /**
   * Descripció de l&#39;error
   * @return errorDescripcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorDescripcio() {
    return errorDescripcio;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
  }


  public RespostaConsultaV2 errorData(Long errorData) {
    
    this.errorData = errorData;
    return this;
  }

   /**
   * Data de l&#39;error
   * @return errorData
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getErrorData() {
    return errorData;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorData(Long errorData) {
    this.errorData = errorData;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespostaConsultaV2 respostaConsultaV2 = (RespostaConsultaV2) o;
    return Objects.equals(this.numeroElementsTotals, respostaConsultaV2.numeroElementsTotals) &&
        Objects.equals(this.numeroElementsRetornats, respostaConsultaV2.numeroElementsRetornats) &&
        Objects.equals(this.resultat, respostaConsultaV2.resultat) &&
        Objects.equals(this.error, respostaConsultaV2.error) &&
        Objects.equals(this.errorDescripcio, respostaConsultaV2.errorDescripcio) &&
        Objects.equals(this.errorData, respostaConsultaV2.errorData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroElementsTotals, numeroElementsRetornats, resultat, error, errorDescripcio, errorData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespostaConsultaV2 {\n");
    sb.append("    numeroElementsTotals: ").append(toIndentedString(numeroElementsTotals)).append("\n");
    sb.append("    numeroElementsRetornats: ").append(toIndentedString(numeroElementsRetornats)).append("\n");
    sb.append("    resultat: ").append(toIndentedString(resultat)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorDescripcio: ").append(toIndentedString(errorDescripcio)).append("\n");
    sb.append("    errorData: ").append(toIndentedString(errorData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

