/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.EnviamentReferenciaV2;
import org.joda.time.DateTime;
/**
 * RespostaAltaV2
 */



public class RespostaAltaV2 {
  @JsonProperty("error")
  private Boolean error = null;

  @JsonProperty("errorData")
  private DateTime errorData = null;

  @JsonProperty("errorDescripcio")
  private String errorDescripcio = null;

  @JsonProperty("identificador")
  private String identificador = null;

  /**
   * Estat de la notificació
   */
  public enum EstatEnum {
    PENDENT("PENDENT"),
    ENVIADA("ENVIADA"),
    REGISTRADA("REGISTRADA"),
    FINALITZADA("FINALITZADA"),
    PROCESSADA("PROCESSADA"),
    ENVIADA_AMB_ERRORS("ENVIADA_AMB_ERRORS"),
    FINALITZADA_AMB_ERRORS("FINALITZADA_AMB_ERRORS");

    private String value;

    EstatEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static EstatEnum fromValue(String input) {
      for (EstatEnum b : EstatEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("estat")
  private EstatEnum estat = null;

  @JsonProperty("referencies")
  private List<EnviamentReferenciaV2> referencies = null;

  @JsonProperty("dataCreacio")
  private String dataCreacio = null;

  public RespostaAltaV2 error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Indica si s&#x27;ha produït algún error en l&#x27;enviament
   * @return error
  **/
  @Schema(example = "true", description = "Indica si s'ha produït algún error en l'enviament")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public RespostaAltaV2 errorData(DateTime errorData) {
    this.errorData = errorData;
    return this;
  }

   /**
   * Data en que s&#x27;ha produït l&#x27;error
   * @return errorData
  **/
  @Schema(description = "Data en que s'ha produït l'error")
  public DateTime getErrorData() {
    return errorData;
  }

  public void setErrorData(DateTime errorData) {
    this.errorData = errorData;
  }

  public RespostaAltaV2 errorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
    return this;
  }

   /**
   * Identificador de la notificació a Notib
   * @return errorDescripcio
  **/
  @Schema(example = "java.lang.NullPointerException", description = "Identificador de la notificació a Notib")
  public String getErrorDescripcio() {
    return errorDescripcio;
  }

  public void setErrorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
  }

  public RespostaAltaV2 identificador(String identificador) {
    this.identificador = identificador;
    return this;
  }

   /**
   * Identificador únic que se li ha assignat a la notificació a Notib
   * @return identificador
  **/
  @Schema(example = "00000000-0000-0000-0000-000000000000", description = "Identificador únic que se li ha assignat a la notificació a Notib")
  public String getIdentificador() {
    return identificador;
  }

  public void setIdentificador(String identificador) {
    this.identificador = identificador;
  }

  public RespostaAltaV2 estat(EstatEnum estat) {
    this.estat = estat;
    return this;
  }

   /**
   * Estat de la notificació
   * @return estat
  **/
  @Schema(example = "PENDENT", description = "Estat de la notificació")
  public EstatEnum getEstat() {
    return estat;
  }

  public void setEstat(EstatEnum estat) {
    this.estat = estat;
  }

  public RespostaAltaV2 referencies(List<EnviamentReferenciaV2> referencies) {
    this.referencies = referencies;
    return this;
  }

  public RespostaAltaV2 addReferenciesItem(EnviamentReferenciaV2 referenciesItem) {
    if (this.referencies == null) {
      this.referencies = new ArrayList<EnviamentReferenciaV2>();
    }
    this.referencies.add(referenciesItem);
    return this;
  }

   /**
   * Referències (identificadors) úniques que s&#x27;han assignat a de cada un dels enviaments de la notificació
   * @return referencies
  **/
  @Schema(description = "Referències (identificadors) úniques que s'han assignat a de cada un dels enviaments de la notificació")
  public List<EnviamentReferenciaV2> getReferencies() {
    return referencies;
  }

  public void setReferencies(List<EnviamentReferenciaV2> referencies) {
    this.referencies = referencies;
  }

  public RespostaAltaV2 dataCreacio(String dataCreacio) {
    this.dataCreacio = dataCreacio;
    return this;
  }

   /**
   * Data en que s&#x27;ha donat d&#x27;alta la notificació
   * @return dataCreacio
  **/
  @Schema(example = "2023-05-29T07:32:03.526+0000", description = "Data en que s'ha donat d'alta la notificació")
  public String getDataCreacio() {
    return dataCreacio;
  }

  public void setDataCreacio(String dataCreacio) {
    this.dataCreacio = dataCreacio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespostaAltaV2 respostaAltaV2 = (RespostaAltaV2) o;
    return Objects.equals(this.error, respostaAltaV2.error) &&
        Objects.equals(this.errorData, respostaAltaV2.errorData) &&
        Objects.equals(this.errorDescripcio, respostaAltaV2.errorDescripcio) &&
        Objects.equals(this.identificador, respostaAltaV2.identificador) &&
        Objects.equals(this.estat, respostaAltaV2.estat) &&
        Objects.equals(this.referencies, respostaAltaV2.referencies) &&
        Objects.equals(this.dataCreacio, respostaAltaV2.dataCreacio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, errorData, errorDescripcio, identificador, estat, referencies, dataCreacio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespostaAltaV2 {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorData: ").append(toIndentedString(errorData)).append("\n");
    sb.append("    errorDescripcio: ").append(toIndentedString(errorDescripcio)).append("\n");
    sb.append("    identificador: ").append(toIndentedString(identificador)).append("\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    referencies: ").append(toIndentedString(referencies)).append("\n");
    sb.append("    dataCreacio: ").append(toIndentedString(dataCreacio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
