/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Date;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.Procediment;
/**
 * RespostaConsultaEstatNotificacioV2
 */



public class RespostaConsultaEstatNotificacioV2 {
  @JsonProperty("error")
  private Boolean error = null;

  @JsonProperty("errorData")
  private Date errorData = null;

  @JsonProperty("errorDescripcio")
  private String errorDescripcio = null;

  @JsonProperty("identificador")
  private String identificador = null;

  /**
   * Enumerat amb la informació de l&#x27;estat de l&#x27;enviament
   */
  public enum EstatEnum {
    PENDENT("PENDENT"),
    ENVIADA("ENVIADA"),
    REGISTRADA("REGISTRADA"),
    FINALITZADA("FINALITZADA"),
    PROCESSADA("PROCESSADA"),
    ENVIADA_AMB_ERRORS("ENVIADA_AMB_ERRORS"),
    FINALITZADA_AMB_ERRORS("FINALITZADA_AMB_ERRORS");

    private String value;

    EstatEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static EstatEnum fromValue(String input) {
      for (EstatEnum b : EstatEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("estat")
  private EstatEnum estat = null;

  @JsonProperty("tipus")
  private String tipus = null;

  @JsonProperty("emisorDir3")
  private String emisorDir3 = null;

  @JsonProperty("procediment")
  private Procediment procediment = null;

  @JsonProperty("organGestorDir3")
  private String organGestorDir3 = null;

  @JsonProperty("concepte")
  private String concepte = null;

  @JsonProperty("numExpedient")
  private String numExpedient = null;

  @JsonProperty("dataCreada")
  private Date dataCreada = null;

  @JsonProperty("dataEnviada")
  private Date dataEnviada = null;

  @JsonProperty("dataFinalitzada")
  private Date dataFinalitzada = null;

  @JsonProperty("dataProcessada")
  private Date dataProcessada = null;

  public RespostaConsultaEstatNotificacioV2 error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Indica si s&#x27;ha produït algún error en l&#x27;enviament
   * @return error
  **/
  @Schema(example = "true", description = "Indica si s'ha produït algún error en l'enviament")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public RespostaConsultaEstatNotificacioV2 errorData(Date errorData) {
    this.errorData = errorData;
    return this;
  }

   /**
   * Data en que s&#x27;ha produït l&#x27;error
   * @return errorData
  **/
  @Schema(description = "Data en que s'ha produït l'error")
  public Date getErrorData() {
    return errorData;
  }

  public void setErrorData(Date errorData) {
    this.errorData = errorData;
  }

  public RespostaConsultaEstatNotificacioV2 errorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
    return this;
  }

   /**
   * Identificador de la notificació a Notib
   * @return errorDescripcio
  **/
  @Schema(example = "java.lang.NullPointerException", description = "Identificador de la notificació a Notib")
  public String getErrorDescripcio() {
    return errorDescripcio;
  }

  public void setErrorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
  }

  public RespostaConsultaEstatNotificacioV2 identificador(String identificador) {
    this.identificador = identificador;
    return this;
  }

   /**
   * Identificador de la notificació a Notib
   * @return identificador
  **/
  @Schema(example = "00000000-0000-0000-0000-000000000000", description = "Identificador de la notificació a Notib")
  public String getIdentificador() {
    return identificador;
  }

  public void setIdentificador(String identificador) {
    this.identificador = identificador;
  }

  public RespostaConsultaEstatNotificacioV2 estat(EstatEnum estat) {
    this.estat = estat;
    return this;
  }

   /**
   * Enumerat amb la informació de l&#x27;estat de l&#x27;enviament
   * @return estat
  **/
  @Schema(example = "FINALITZADA", description = "Enumerat amb la informació de l'estat de l'enviament")
  public EstatEnum getEstat() {
    return estat;
  }

  public void setEstat(EstatEnum estat) {
    this.estat = estat;
  }

  public RespostaConsultaEstatNotificacioV2 tipus(String tipus) {
    this.tipus = tipus;
    return this;
  }

   /**
   * Indica si l’enviament és una comunicació o una notificació
   * @return tipus
  **/
  @Schema(example = "NOTIFICACIO", description = "Indica si l’enviament és una comunicació o una notificació")
  public String getTipus() {
    return tipus;
  }

  public void setTipus(String tipus) {
    this.tipus = tipus;
  }

  public RespostaConsultaEstatNotificacioV2 emisorDir3(String emisorDir3) {
    this.emisorDir3 = emisorDir3;
    return this;
  }

   /**
   * Codi Dir3 de l’organisme emisor (Entitat de Notib)
   * @return emisorDir3
  **/
  @Schema(example = "A04003003", description = "Codi Dir3 de l’organisme emisor (Entitat de Notib)")
  public String getEmisorDir3() {
    return emisorDir3;
  }

  public void setEmisorDir3(String emisorDir3) {
    this.emisorDir3 = emisorDir3;
  }

  public RespostaConsultaEstatNotificacioV2 procediment(Procediment procediment) {
    this.procediment = procediment;
    return this;
  }

   /**
   * Get procediment
   * @return procediment
  **/
  @Schema(description = "")
  public Procediment getProcediment() {
    return procediment;
  }

  public void setProcediment(Procediment procediment) {
    this.procediment = procediment;
  }

  public RespostaConsultaEstatNotificacioV2 organGestorDir3(String organGestorDir3) {
    this.organGestorDir3 = organGestorDir3;
    return this;
  }

   /**
   * Codi DIR3 de l’òrgan gestor que realitza la notificació/comunicació
   * @return organGestorDir3
  **/
  @Schema(example = "A04035965", description = "Codi DIR3 de l’òrgan gestor que realitza la notificació/comunicació")
  public String getOrganGestorDir3() {
    return organGestorDir3;
  }

  public void setOrganGestorDir3(String organGestorDir3) {
    this.organGestorDir3 = organGestorDir3;
  }

  public RespostaConsultaEstatNotificacioV2 concepte(String concepte) {
    this.concepte = concepte;
    return this;
  }

   /**
   * Concepte de la notificació
   * @return concepte
  **/
  @Schema(example = "Concepte de la notificació", description = "Concepte de la notificació")
  public String getConcepte() {
    return concepte;
  }

  public void setConcepte(String concepte) {
    this.concepte = concepte;
  }

  public RespostaConsultaEstatNotificacioV2 numExpedient(String numExpedient) {
    this.numExpedient = numExpedient;
    return this;
  }

   /**
   * Identificador de l&#x27;expedient al qual pertany la notificació
   * @return numExpedient
  **/
  @Schema(example = "123/2023", description = "Identificador de l'expedient al qual pertany la notificació")
  public String getNumExpedient() {
    return numExpedient;
  }

  public void setNumExpedient(String numExpedient) {
    this.numExpedient = numExpedient;
  }

  public RespostaConsultaEstatNotificacioV2 dataCreada(Date dataCreada) {
    this.dataCreada = dataCreada;
    return this;
  }

   /**
   * Data en que s&#x27;ha donat d&#x27;alta la notificació
   * @return dataCreada
  **/
  @Schema(description = "Data en que s'ha donat d'alta la notificació")
  public Date getDataCreada() {
    return dataCreada;
  }

  public void setDataCreada(Date dataCreada) {
    this.dataCreada = dataCreada;
  }

  public RespostaConsultaEstatNotificacioV2 dataEnviada(Date dataEnviada) {
    this.dataEnviada = dataEnviada;
    return this;
  }

   /**
   * Data en que s&#x27;ha enviat la notificació a Notifica (o SIR)
   * @return dataEnviada
  **/
  @Schema(description = "Data en que s'ha enviat la notificació a Notifica (o SIR)")
  public Date getDataEnviada() {
    return dataEnviada;
  }

  public void setDataEnviada(Date dataEnviada) {
    this.dataEnviada = dataEnviada;
  }

  public RespostaConsultaEstatNotificacioV2 dataFinalitzada(Date dataFinalitzada) {
    this.dataFinalitzada = dataFinalitzada;
    return this;
  }

   /**
   * Data en que s&#x27;ha finalitzat la notificació
   * @return dataFinalitzada
  **/
  @Schema(description = "Data en que s'ha finalitzat la notificació")
  public Date getDataFinalitzada() {
    return dataFinalitzada;
  }

  public void setDataFinalitzada(Date dataFinalitzada) {
    this.dataFinalitzada = dataFinalitzada;
  }

  public RespostaConsultaEstatNotificacioV2 dataProcessada(Date dataProcessada) {
    this.dataProcessada = dataProcessada;
    return this;
  }

   /**
   * Data en que s&#x27;ha marcat la notificació com a processada
   * @return dataProcessada
  **/
  @Schema(description = "Data en que s'ha marcat la notificació com a processada")
  public Date getDataProcessada() {
    return dataProcessada;
  }

  public void setDataProcessada(Date dataProcessada) {
    this.dataProcessada = dataProcessada;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespostaConsultaEstatNotificacioV2 respostaConsultaEstatNotificacioV2 = (RespostaConsultaEstatNotificacioV2) o;
    return Objects.equals(this.error, respostaConsultaEstatNotificacioV2.error) &&
        Objects.equals(this.errorData, respostaConsultaEstatNotificacioV2.errorData) &&
        Objects.equals(this.errorDescripcio, respostaConsultaEstatNotificacioV2.errorDescripcio) &&
        Objects.equals(this.identificador, respostaConsultaEstatNotificacioV2.identificador) &&
        Objects.equals(this.estat, respostaConsultaEstatNotificacioV2.estat) &&
        Objects.equals(this.tipus, respostaConsultaEstatNotificacioV2.tipus) &&
        Objects.equals(this.emisorDir3, respostaConsultaEstatNotificacioV2.emisorDir3) &&
        Objects.equals(this.procediment, respostaConsultaEstatNotificacioV2.procediment) &&
        Objects.equals(this.organGestorDir3, respostaConsultaEstatNotificacioV2.organGestorDir3) &&
        Objects.equals(this.concepte, respostaConsultaEstatNotificacioV2.concepte) &&
        Objects.equals(this.numExpedient, respostaConsultaEstatNotificacioV2.numExpedient) &&
        Objects.equals(this.dataCreada, respostaConsultaEstatNotificacioV2.dataCreada) &&
        Objects.equals(this.dataEnviada, respostaConsultaEstatNotificacioV2.dataEnviada) &&
        Objects.equals(this.dataFinalitzada, respostaConsultaEstatNotificacioV2.dataFinalitzada) &&
        Objects.equals(this.dataProcessada, respostaConsultaEstatNotificacioV2.dataProcessada);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, errorData, errorDescripcio, identificador, estat, tipus, emisorDir3, procediment, organGestorDir3, concepte, numExpedient, dataCreada, dataEnviada, dataFinalitzada, dataProcessada);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespostaConsultaEstatNotificacioV2 {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorData: ").append(toIndentedString(errorData)).append("\n");
    sb.append("    errorDescripcio: ").append(toIndentedString(errorDescripcio)).append("\n");
    sb.append("    identificador: ").append(toIndentedString(identificador)).append("\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    tipus: ").append(toIndentedString(tipus)).append("\n");
    sb.append("    emisorDir3: ").append(toIndentedString(emisorDir3)).append("\n");
    sb.append("    procediment: ").append(toIndentedString(procediment)).append("\n");
    sb.append("    organGestorDir3: ").append(toIndentedString(organGestorDir3)).append("\n");
    sb.append("    concepte: ").append(toIndentedString(concepte)).append("\n");
    sb.append("    numExpedient: ").append(toIndentedString(numExpedient)).append("\n");
    sb.append("    dataCreada: ").append(toIndentedString(dataCreada)).append("\n");
    sb.append("    dataEnviada: ").append(toIndentedString(dataEnviada)).append("\n");
    sb.append("    dataFinalitzada: ").append(toIndentedString(dataFinalitzada)).append("\n");
    sb.append("    dataProcessada: ").append(toIndentedString(dataProcessada)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
