/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
/**
 * RespostaConsultaDadesRegistreV2
 */



public class RespostaConsultaDadesRegistreV2 {
  @JsonProperty("error")
  private Boolean error = null;

  @JsonProperty("errorData")
  private Date errorData = null;

  @JsonProperty("errorDescripcio")
  private String errorDescripcio = null;

  @JsonProperty("numRegistre")
  private Integer numRegistre = null;

  @JsonProperty("numeroFormatat")
  private String numeroFormatat = null;

  @JsonProperty("dataRegistre")
  private Date dataRegistre = null;

  @JsonProperty("justificant")
  private List<byte[]> justificant = null;

  @JsonProperty("oficina")
  private String oficina = null;

  @JsonProperty("llibre")
  private String llibre = null;

  @JsonProperty("enviamentSir")
  private Boolean enviamentSir = null;

  @JsonProperty("dataRecepcioSir")
  private Date dataRecepcioSir = null;

  @JsonProperty("dataRegistreDestiSir")
  private Date dataRegistreDestiSir = null;

  public RespostaConsultaDadesRegistreV2 error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Indica si s&#x27;ha produït algún error en l&#x27;enviament
   * @return error
  **/
  @Schema(example = "true", description = "Indica si s'ha produït algún error en l'enviament")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public RespostaConsultaDadesRegistreV2 errorData(Date errorData) {
    this.errorData = errorData;
    return this;
  }

   /**
   * Data en que s&#x27;ha produït l&#x27;error
   * @return errorData
  **/
  @Schema(description = "Data en que s'ha produït l'error")
  public Date getErrorData() {
    return errorData;
  }

  public void setErrorData(Date errorData) {
    this.errorData = errorData;
  }

  public RespostaConsultaDadesRegistreV2 errorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
    return this;
  }

   /**
   * Identificador de la notificació a Notib
   * @return errorDescripcio
  **/
  @Schema(example = "java.lang.NullPointerException", description = "Identificador de la notificació a Notib")
  public String getErrorDescripcio() {
    return errorDescripcio;
  }

  public void setErrorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
  }

  public RespostaConsultaDadesRegistreV2 numRegistre(Integer numRegistre) {
    this.numRegistre = numRegistre;
    return this;
  }

   /**
   * Número de registre
   * @return numRegistre
  **/
  @Schema(example = "1753", description = "Número de registre")
  public Integer getNumRegistre() {
    return numRegistre;
  }

  public void setNumRegistre(Integer numRegistre) {
    this.numRegistre = numRegistre;
  }

  public RespostaConsultaDadesRegistreV2 numeroFormatat(String numeroFormatat) {
    this.numeroFormatat = numeroFormatat;
    return this;
  }

   /**
   * Número de registre amb format
   * @return numeroFormatat
  **/
  @Schema(example = "GOIBS1753/2023", description = "Número de registre amb format")
  public String getNumeroFormatat() {
    return numeroFormatat;
  }

  public void setNumeroFormatat(String numeroFormatat) {
    this.numeroFormatat = numeroFormatat;
  }

  public RespostaConsultaDadesRegistreV2 dataRegistre(Date dataRegistre) {
    this.dataRegistre = dataRegistre;
    return this;
  }

   /**
   * Data del registre
   * @return dataRegistre
  **/
  @Schema(description = "Data del registre")
  public Date getDataRegistre() {
    return dataRegistre;
  }

  public void setDataRegistre(Date dataRegistre) {
    this.dataRegistre = dataRegistre;
  }

  public RespostaConsultaDadesRegistreV2 justificant(List<byte[]> justificant) {
    this.justificant = justificant;
    return this;
  }

  public RespostaConsultaDadesRegistreV2 addJustificantItem(byte[] justificantItem) {
    if (this.justificant == null) {
      this.justificant = new ArrayList<byte[]>();
    }
    this.justificant.add(justificantItem);
    return this;
  }

   /**
   * Contingut del fitxer justificant
   * @return justificant
  **/
  @Schema(description = "Contingut del fitxer justificant")
  public List<byte[]> getJustificant() {
    return justificant;
  }

  public void setJustificant(List<byte[]> justificant) {
    this.justificant = justificant;
  }

  public RespostaConsultaDadesRegistreV2 oficina(String oficina) {
    this.oficina = oficina;
    return this;
  }

   /**
   * Oficina on s&#x27;ha realitzat el registre
   * @return oficina
  **/
  @Schema(example = "Oficina Virtual", description = "Oficina on s'ha realitzat el registre")
  public String getOficina() {
    return oficina;
  }

  public void setOficina(String oficina) {
    this.oficina = oficina;
  }

  public RespostaConsultaDadesRegistreV2 llibre(String llibre) {
    this.llibre = llibre;
    return this;
  }

   /**
   * Llibre on s&#x27;ha anotat el registre
   * @return llibre
  **/
  @Schema(example = "Govern de les Illes Balears", description = "Llibre on s'ha anotat el registre")
  public String getLlibre() {
    return llibre;
  }

  public void setLlibre(String llibre) {
    this.llibre = llibre;
  }

  public RespostaConsultaDadesRegistreV2 enviamentSir(Boolean enviamentSir) {
    this.enviamentSir = enviamentSir;
    return this;
  }

   /**
   * Indica si s&#x27;ha realitzat l&#x27;enviament via SIR
   * @return enviamentSir
  **/
  @Schema(example = "false", description = "Indica si s'ha realitzat l'enviament via SIR")
  public Boolean isEnviamentSir() {
    return enviamentSir;
  }

  public void setEnviamentSir(Boolean enviamentSir) {
    this.enviamentSir = enviamentSir;
  }

  public RespostaConsultaDadesRegistreV2 dataRecepcioSir(Date dataRecepcioSir) {
    this.dataRecepcioSir = dataRecepcioSir;
    return this;
  }

   /**
   * En cas d&#x27;enviament SIR, data en que s&#x27;ha recepcionat el registre
   * @return dataRecepcioSir
  **/
  @Schema(description = "En cas d'enviament SIR, data en que s'ha recepcionat el registre")
  public Date getDataRecepcioSir() {
    return dataRecepcioSir;
  }

  public void setDataRecepcioSir(Date dataRecepcioSir) {
    this.dataRecepcioSir = dataRecepcioSir;
  }

  public RespostaConsultaDadesRegistreV2 dataRegistreDestiSir(Date dataRegistreDestiSir) {
    this.dataRegistreDestiSir = dataRegistreDestiSir;
    return this;
  }

   /**
   * En cas d&#x27;enviament SIR, data en que s&#x27;ha registrat en el registre de destí
   * @return dataRegistreDestiSir
  **/
  @Schema(description = "En cas d'enviament SIR, data en que s'ha registrat en el registre de destí")
  public Date getDataRegistreDestiSir() {
    return dataRegistreDestiSir;
  }

  public void setDataRegistreDestiSir(Date dataRegistreDestiSir) {
    this.dataRegistreDestiSir = dataRegistreDestiSir;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespostaConsultaDadesRegistreV2 respostaConsultaDadesRegistreV2 = (RespostaConsultaDadesRegistreV2) o;
    return Objects.equals(this.error, respostaConsultaDadesRegistreV2.error) &&
        Objects.equals(this.errorData, respostaConsultaDadesRegistreV2.errorData) &&
        Objects.equals(this.errorDescripcio, respostaConsultaDadesRegistreV2.errorDescripcio) &&
        Objects.equals(this.numRegistre, respostaConsultaDadesRegistreV2.numRegistre) &&
        Objects.equals(this.numeroFormatat, respostaConsultaDadesRegistreV2.numeroFormatat) &&
        Objects.equals(this.dataRegistre, respostaConsultaDadesRegistreV2.dataRegistre) &&
        Objects.equals(this.justificant, respostaConsultaDadesRegistreV2.justificant) &&
        Objects.equals(this.oficina, respostaConsultaDadesRegistreV2.oficina) &&
        Objects.equals(this.llibre, respostaConsultaDadesRegistreV2.llibre) &&
        Objects.equals(this.enviamentSir, respostaConsultaDadesRegistreV2.enviamentSir) &&
        Objects.equals(this.dataRecepcioSir, respostaConsultaDadesRegistreV2.dataRecepcioSir) &&
        Objects.equals(this.dataRegistreDestiSir, respostaConsultaDadesRegistreV2.dataRegistreDestiSir);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, errorData, errorDescripcio, numRegistre, numeroFormatat, dataRegistre, justificant, oficina, llibre, enviamentSir, dataRecepcioSir, dataRegistreDestiSir);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespostaConsultaDadesRegistreV2 {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorData: ").append(toIndentedString(errorData)).append("\n");
    sb.append("    errorDescripcio: ").append(toIndentedString(errorDescripcio)).append("\n");
    sb.append("    numRegistre: ").append(toIndentedString(numRegistre)).append("\n");
    sb.append("    numeroFormatat: ").append(toIndentedString(numeroFormatat)).append("\n");
    sb.append("    dataRegistre: ").append(toIndentedString(dataRegistre)).append("\n");
    sb.append("    justificant: ").append(toIndentedString(justificant)).append("\n");
    sb.append("    oficina: ").append(toIndentedString(oficina)).append("\n");
    sb.append("    llibre: ").append(toIndentedString(llibre)).append("\n");
    sb.append("    enviamentSir: ").append(toIndentedString(enviamentSir)).append("\n");
    sb.append("    dataRecepcioSir: ").append(toIndentedString(dataRecepcioSir)).append("\n");
    sb.append("    dataRegistreDestiSir: ").append(toIndentedString(dataRegistreDestiSir)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
