/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.Certificacio;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.Datat;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.Persona;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.Registre;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.Sir;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RespostaConsultaEstatEnviamentV2
 */
@JsonPropertyOrder({
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ERROR,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ERROR_DATA,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ERROR_DESCRIPCIO,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_IDENTIFICADOR,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_REFERENCIA,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_NOTIFICA_INDENTIFICADOR,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ESTAT,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ESTAT_DATA,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ESTAT_DESCRIPCIO,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ENVIAMENT_SIR,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_DEH_OBLIGAT,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_DEH_NIF,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ENTRAGA_POSTAL_ACTIVA,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_ADRESSA_POSTAL,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_INTERESSAT,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_REPRESENTANTS,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_REGISTRE,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_SIR,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_DATAT,
  RespostaConsultaEstatEnviamentV2.JSON_PROPERTY_CERTIFICACIO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RespostaConsultaEstatEnviamentV2 {
  public static final String JSON_PROPERTY_ERROR = "error";
  private Boolean error;

  public static final String JSON_PROPERTY_ERROR_DATA = "errorData";
  private Long errorData;

  public static final String JSON_PROPERTY_ERROR_DESCRIPCIO = "errorDescripcio";
  private String errorDescripcio;

  public static final String JSON_PROPERTY_IDENTIFICADOR = "identificador";
  private String identificador;

  public static final String JSON_PROPERTY_REFERENCIA = "referencia";
  private String referencia;

  public static final String JSON_PROPERTY_NOTIFICA_INDENTIFICADOR = "notificaIndentificador";
  private String notificaIndentificador;

  /**
   * Enumerat amb la informació de l&#39;estat de l&#39;enviament
   */
  public enum EstatEnum {
    NOTIB_PENDENT("NOTIB_PENDENT"),
    
    NOTIB_ENVIADA("NOTIB_ENVIADA"),
    
    ABSENT("ABSENT"),
    
    ADRESA_INCORRECTA("ADRESA_INCORRECTA"),
    
    DESCONEGUT("DESCONEGUT"),
    
    ENVIADA_CI("ENVIADA_CI"),
    
    ENVIADA_DEH("ENVIADA_DEH"),
    
    ENVIAMENT_PROGRAMAT("ENVIAMENT_PROGRAMAT"),
    
    ENTREGADA_OP("ENTREGADA_OP"),
    
    ERROR_ENTREGA("ERROR_ENTREGA"),
    
    EXPIRADA("EXPIRADA"),
    
    EXTRAVIADA("EXTRAVIADA"),
    
    MORT("MORT"),
    
    LLEGIDA("LLEGIDA"),
    
    NOTIFICADA("NOTIFICADA"),
    
    PENDENT("PENDENT"),
    
    PENDENT_ENVIAMENT("PENDENT_ENVIAMENT"),
    
    PENDENT_SEU("PENDENT_SEU"),
    
    PENDENT_CIE("PENDENT_CIE"),
    
    PENDENT_DEH("PENDENT_DEH"),
    
    REBUTJADA("REBUTJADA"),
    
    SENSE_INFORMACIO("SENSE_INFORMACIO"),
    
    FINALITZADA("FINALITZADA"),
    
    ENVIADA("ENVIADA"),
    
    REGISTRADA("REGISTRADA"),
    
    PROCESSADA("PROCESSADA"),
    
    ANULADA("ANULADA"),
    
    ENVIAT_SIR("ENVIAT_SIR"),
    
    ENVIADA_AMB_ERRORS("ENVIADA_AMB_ERRORS"),
    
    FINALITZADA_AMB_ERRORS("FINALITZADA_AMB_ERRORS");

    private String value;

    EstatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EstatEnum fromValue(String value) {
      for (EstatEnum b : EstatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ESTAT = "estat";
  private EstatEnum estat;

  public static final String JSON_PROPERTY_ESTAT_DATA = "estatData";
  private Long estatData;

  public static final String JSON_PROPERTY_ESTAT_DESCRIPCIO = "estatDescripcio";
  private String estatDescripcio;

  public static final String JSON_PROPERTY_ENVIAMENT_SIR = "enviamentSir";
  private Boolean enviamentSir;

  public static final String JSON_PROPERTY_DEH_OBLIGAT = "dehObligat";
  private Boolean dehObligat;

  public static final String JSON_PROPERTY_DEH_NIF = "dehNif";
  private String dehNif;

  public static final String JSON_PROPERTY_ENTRAGA_POSTAL_ACTIVA = "entragaPostalActiva";
  private Boolean entragaPostalActiva;

  public static final String JSON_PROPERTY_ADRESSA_POSTAL = "adressaPostal";
  private String adressaPostal;

  public static final String JSON_PROPERTY_INTERESSAT = "interessat";
  private Persona interessat;

  public static final String JSON_PROPERTY_REPRESENTANTS = "representants";
  private List<Persona> representants;

  public static final String JSON_PROPERTY_REGISTRE = "registre";
  private Registre registre;

  public static final String JSON_PROPERTY_SIR = "sir";
  private Sir sir;

  public static final String JSON_PROPERTY_DATAT = "datat";
  private Datat datat;

  public static final String JSON_PROPERTY_CERTIFICACIO = "certificacio";
  private Certificacio certificacio;

  public RespostaConsultaEstatEnviamentV2() {
  }

  public RespostaConsultaEstatEnviamentV2 error(Boolean error) {
    
    this.error = error;
    return this;
  }

   /**
   * Indica si s&#39;ha produït algún error en l&#39;enviament
   * @return error
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(Boolean error) {
    this.error = error;
  }


  public RespostaConsultaEstatEnviamentV2 errorData(Long errorData) {
    
    this.errorData = errorData;
    return this;
  }

   /**
   * Data en que s&#39;ha produït l&#39;error
   * @return errorData
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getErrorData() {
    return errorData;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorData(Long errorData) {
    this.errorData = errorData;
  }


  public RespostaConsultaEstatEnviamentV2 errorDescripcio(String errorDescripcio) {
    
    this.errorDescripcio = errorDescripcio;
    return this;
  }

   /**
   * Identificador de la notificació a Notib
   * @return errorDescripcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorDescripcio() {
    return errorDescripcio;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
  }


  public RespostaConsultaEstatEnviamentV2 identificador(String identificador) {
    
    this.identificador = identificador;
    return this;
  }

   /**
   * Identificador de la notificació a Notib
   * @return identificador
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFICADOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentificador() {
    return identificador;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFICADOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificador(String identificador) {
    this.identificador = identificador;
  }


  public RespostaConsultaEstatEnviamentV2 referencia(String referencia) {
    
    this.referencia = referencia;
    return this;
  }

   /**
   * Identificador de l&#39;enviament a Notib
   * @return referencia
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferencia() {
    return referencia;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferencia(String referencia) {
    this.referencia = referencia;
  }


  public RespostaConsultaEstatEnviamentV2 notificaIndentificador(String notificaIndentificador) {
    
    this.notificaIndentificador = notificaIndentificador;
    return this;
  }

   /**
   * Identificador de l&#39;enviament a Notific@
   * @return notificaIndentificador
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOTIFICA_INDENTIFICADOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNotificaIndentificador() {
    return notificaIndentificador;
  }


  @JsonProperty(JSON_PROPERTY_NOTIFICA_INDENTIFICADOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotificaIndentificador(String notificaIndentificador) {
    this.notificaIndentificador = notificaIndentificador;
  }


  public RespostaConsultaEstatEnviamentV2 estat(EstatEnum estat) {
    
    this.estat = estat;
    return this;
  }

   /**
   * Enumerat amb la informació de l&#39;estat de l&#39;enviament
   * @return estat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EstatEnum getEstat() {
    return estat;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstat(EstatEnum estat) {
    this.estat = estat;
  }


  public RespostaConsultaEstatEnviamentV2 estatData(Long estatData) {
    
    this.estatData = estatData;
    return this;
  }

   /**
   * Data en que s&#39;ha assignat l&#39;estat actual de l&#39;enviament
   * @return estatData
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEstatData() {
    return estatData;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatData(Long estatData) {
    this.estatData = estatData;
  }


  public RespostaConsultaEstatEnviamentV2 estatDescripcio(String estatDescripcio) {
    
    this.estatDescripcio = estatDescripcio;
    return this;
  }

   /**
   * Descripció de l&#39;estat de l&#39;enviament
   * @return estatDescripcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstatDescripcio() {
    return estatDescripcio;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstatDescripcio(String estatDescripcio) {
    this.estatDescripcio = estatDescripcio;
  }


  public RespostaConsultaEstatEnviamentV2 enviamentSir(Boolean enviamentSir) {
    
    this.enviamentSir = enviamentSir;
    return this;
  }

   /**
   * Indica si l&#39;enviament s&#39;ha realitzat a través de SIR
   * @return enviamentSir
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENVIAMENT_SIR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isEnviamentSir() {
    return enviamentSir;
  }


  @JsonProperty(JSON_PROPERTY_ENVIAMENT_SIR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnviamentSir(Boolean enviamentSir) {
    this.enviamentSir = enviamentSir;
  }


  public RespostaConsultaEstatEnviamentV2 dehObligat(Boolean dehObligat) {
    
    this.dehObligat = dehObligat;
    return this;
  }

   /**
   * Indica si el destinatari està obligat a rebre les notificacions al DEH
   * @return dehObligat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEH_OBLIGAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isDehObligat() {
    return dehObligat;
  }


  @JsonProperty(JSON_PROPERTY_DEH_OBLIGAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDehObligat(Boolean dehObligat) {
    this.dehObligat = dehObligat;
  }


  public RespostaConsultaEstatEnviamentV2 dehNif(String dehNif) {
    
    this.dehNif = dehNif;
    return this;
  }

   /**
   * Nif a utilitzar per l&#39;enviamnt a DEH
   * @return dehNif
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEH_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDehNif() {
    return dehNif;
  }


  @JsonProperty(JSON_PROPERTY_DEH_NIF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDehNif(String dehNif) {
    this.dehNif = dehNif;
  }


  public RespostaConsultaEstatEnviamentV2 entragaPostalActiva(Boolean entragaPostalActiva) {
    
    this.entragaPostalActiva = entragaPostalActiva;
    return this;
  }

   /**
   * Indica si l&#39;enviament està configurat per enviament postal
   * @return entragaPostalActiva
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTRAGA_POSTAL_ACTIVA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isEntragaPostalActiva() {
    return entragaPostalActiva;
  }


  @JsonProperty(JSON_PROPERTY_ENTRAGA_POSTAL_ACTIVA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntragaPostalActiva(Boolean entragaPostalActiva) {
    this.entragaPostalActiva = entragaPostalActiva;
  }


  public RespostaConsultaEstatEnviamentV2 adressaPostal(String adressaPostal) {
    
    this.adressaPostal = adressaPostal;
    return this;
  }

   /**
   * Adreça on es realitzarà l&#39;enviament postal
   * @return adressaPostal
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADRESSA_POSTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdressaPostal() {
    return adressaPostal;
  }


  @JsonProperty(JSON_PROPERTY_ADRESSA_POSTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdressaPostal(String adressaPostal) {
    this.adressaPostal = adressaPostal;
  }


  public RespostaConsultaEstatEnviamentV2 interessat(Persona interessat) {
    
    this.interessat = interessat;
    return this;
  }

   /**
   * Get interessat
   * @return interessat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERESSAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Persona getInteressat() {
    return interessat;
  }


  @JsonProperty(JSON_PROPERTY_INTERESSAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInteressat(Persona interessat) {
    this.interessat = interessat;
  }


  public RespostaConsultaEstatEnviamentV2 representants(List<Persona> representants) {
    
    this.representants = representants;
    return this;
  }

  public RespostaConsultaEstatEnviamentV2 addRepresentantsItem(Persona representantsItem) {
    if (this.representants == null) {
      this.representants = new ArrayList<>();
    }
    this.representants.add(representantsItem);
    return this;
  }

   /**
   * Representants a qui enviar l&#39;enviament
   * @return representants
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPRESENTANTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Persona> getRepresentants() {
    return representants;
  }


  @JsonProperty(JSON_PROPERTY_REPRESENTANTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepresentants(List<Persona> representants) {
    this.representants = representants;
  }


  public RespostaConsultaEstatEnviamentV2 registre(Registre registre) {
    
    this.registre = registre;
    return this;
  }

   /**
   * Get registre
   * @return registre
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Registre getRegistre() {
    return registre;
  }


  @JsonProperty(JSON_PROPERTY_REGISTRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistre(Registre registre) {
    this.registre = registre;
  }


  public RespostaConsultaEstatEnviamentV2 sir(Sir sir) {
    
    this.sir = sir;
    return this;
  }

   /**
   * Get sir
   * @return sir
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Sir getSir() {
    return sir;
  }


  @JsonProperty(JSON_PROPERTY_SIR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSir(Sir sir) {
    this.sir = sir;
  }


  public RespostaConsultaEstatEnviamentV2 datat(Datat datat) {
    
    this.datat = datat;
    return this;
  }

   /**
   * Get datat
   * @return datat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Datat getDatat() {
    return datat;
  }


  @JsonProperty(JSON_PROPERTY_DATAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatat(Datat datat) {
    this.datat = datat;
  }


  public RespostaConsultaEstatEnviamentV2 certificacio(Certificacio certificacio) {
    
    this.certificacio = certificacio;
    return this;
  }

   /**
   * Get certificacio
   * @return certificacio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICACIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Certificacio getCertificacio() {
    return certificacio;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICACIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificacio(Certificacio certificacio) {
    this.certificacio = certificacio;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespostaConsultaEstatEnviamentV2 respostaConsultaEstatEnviamentV2 = (RespostaConsultaEstatEnviamentV2) o;
    return Objects.equals(this.error, respostaConsultaEstatEnviamentV2.error) &&
        Objects.equals(this.errorData, respostaConsultaEstatEnviamentV2.errorData) &&
        Objects.equals(this.errorDescripcio, respostaConsultaEstatEnviamentV2.errorDescripcio) &&
        Objects.equals(this.identificador, respostaConsultaEstatEnviamentV2.identificador) &&
        Objects.equals(this.referencia, respostaConsultaEstatEnviamentV2.referencia) &&
        Objects.equals(this.notificaIndentificador, respostaConsultaEstatEnviamentV2.notificaIndentificador) &&
        Objects.equals(this.estat, respostaConsultaEstatEnviamentV2.estat) &&
        Objects.equals(this.estatData, respostaConsultaEstatEnviamentV2.estatData) &&
        Objects.equals(this.estatDescripcio, respostaConsultaEstatEnviamentV2.estatDescripcio) &&
        Objects.equals(this.enviamentSir, respostaConsultaEstatEnviamentV2.enviamentSir) &&
        Objects.equals(this.dehObligat, respostaConsultaEstatEnviamentV2.dehObligat) &&
        Objects.equals(this.dehNif, respostaConsultaEstatEnviamentV2.dehNif) &&
        Objects.equals(this.entragaPostalActiva, respostaConsultaEstatEnviamentV2.entragaPostalActiva) &&
        Objects.equals(this.adressaPostal, respostaConsultaEstatEnviamentV2.adressaPostal) &&
        Objects.equals(this.interessat, respostaConsultaEstatEnviamentV2.interessat) &&
        Objects.equals(this.representants, respostaConsultaEstatEnviamentV2.representants) &&
        Objects.equals(this.registre, respostaConsultaEstatEnviamentV2.registre) &&
        Objects.equals(this.sir, respostaConsultaEstatEnviamentV2.sir) &&
        Objects.equals(this.datat, respostaConsultaEstatEnviamentV2.datat) &&
        Objects.equals(this.certificacio, respostaConsultaEstatEnviamentV2.certificacio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, errorData, errorDescripcio, identificador, referencia, notificaIndentificador, estat, estatData, estatDescripcio, enviamentSir, dehObligat, dehNif, entragaPostalActiva, adressaPostal, interessat, representants, registre, sir, datat, certificacio);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespostaConsultaEstatEnviamentV2 {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorData: ").append(toIndentedString(errorData)).append("\n");
    sb.append("    errorDescripcio: ").append(toIndentedString(errorDescripcio)).append("\n");
    sb.append("    identificador: ").append(toIndentedString(identificador)).append("\n");
    sb.append("    referencia: ").append(toIndentedString(referencia)).append("\n");
    sb.append("    notificaIndentificador: ").append(toIndentedString(notificaIndentificador)).append("\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    estatData: ").append(toIndentedString(estatData)).append("\n");
    sb.append("    estatDescripcio: ").append(toIndentedString(estatDescripcio)).append("\n");
    sb.append("    enviamentSir: ").append(toIndentedString(enviamentSir)).append("\n");
    sb.append("    dehObligat: ").append(toIndentedString(dehObligat)).append("\n");
    sb.append("    dehNif: ").append(toIndentedString(dehNif)).append("\n");
    sb.append("    entragaPostalActiva: ").append(toIndentedString(entragaPostalActiva)).append("\n");
    sb.append("    adressaPostal: ").append(toIndentedString(adressaPostal)).append("\n");
    sb.append("    interessat: ").append(toIndentedString(interessat)).append("\n");
    sb.append("    representants: ").append(toIndentedString(representants)).append("\n");
    sb.append("    registre: ").append(toIndentedString(registre)).append("\n");
    sb.append("    sir: ").append(toIndentedString(sir)).append("\n");
    sb.append("    datat: ").append(toIndentedString(datat)).append("\n");
    sb.append("    certificacio: ").append(toIndentedString(certificacio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

