/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació per a l&#39;enviament SIR
 */
@JsonPropertyOrder({
  Sir.JSON_PROPERTY_DATA_RECEPCIO,
  Sir.JSON_PROPERTY_DATA_REGISTRE_DESTI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Sir {
  public static final String JSON_PROPERTY_DATA_RECEPCIO = "dataRecepcio";
  private Long dataRecepcio;

  public static final String JSON_PROPERTY_DATA_REGISTRE_DESTI = "dataRegistreDesti";
  private Long dataRegistreDesti;

  public Sir() {
  }

  public Sir dataRecepcio(Long dataRecepcio) {
    
    this.dataRecepcio = dataRecepcio;
    return this;
  }

   /**
   * Data en que s&#39;ha recepcionat el registre
   * @return dataRecepcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_RECEPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDataRecepcio() {
    return dataRecepcio;
  }


  @JsonProperty(JSON_PROPERTY_DATA_RECEPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataRecepcio(Long dataRecepcio) {
    this.dataRecepcio = dataRecepcio;
  }


  public Sir dataRegistreDesti(Long dataRegistreDesti) {
    
    this.dataRegistreDesti = dataRegistreDesti;
    return this;
  }

   /**
   * Data en que s&#39;ha registrat en el registre de destí
   * @return dataRegistreDesti
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_REGISTRE_DESTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDataRegistreDesti() {
    return dataRegistreDesti;
  }


  @JsonProperty(JSON_PROPERTY_DATA_REGISTRE_DESTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataRegistreDesti(Long dataRegistreDesti) {
    this.dataRegistreDesti = dataRegistreDesti;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sir sir = (Sir) o;
    return Objects.equals(this.dataRecepcio, sir.dataRecepcio) &&
        Objects.equals(this.dataRegistreDesti, sir.dataRegistreDesti);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataRecepcio, dataRegistreDesti);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sir {\n");
    sb.append("    dataRecepcio: ").append(toIndentedString(dataRecepcio)).append("\n");
    sb.append("    dataRegistreDesti: ").append(toIndentedString(dataRegistreDesti)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

