/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.DocumentConsultaV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.GenericInfo;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.PersonaConsultaV2;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Llistat de les notificacions retornades
 */
@JsonPropertyOrder({
  TransmissioV2.JSON_PROPERTY_ID,
  TransmissioV2.JSON_PROPERTY_EMISOR,
  TransmissioV2.JSON_PROPERTY_ORGAN_GESTOR,
  TransmissioV2.JSON_PROPERTY_PROCEDIMENT,
  TransmissioV2.JSON_PROPERTY_NUM_EXPEDIENT,
  TransmissioV2.JSON_PROPERTY_CONCEPTE,
  TransmissioV2.JSON_PROPERTY_DESCRIPCIO,
  TransmissioV2.JSON_PROPERTY_DATA_ENVIAMENT,
  TransmissioV2.JSON_PROPERTY_ESTAT,
  TransmissioV2.JSON_PROPERTY_DATA_ESTAT,
  TransmissioV2.JSON_PROPERTY_DOCUMENT,
  TransmissioV2.JSON_PROPERTY_TITULAR,
  TransmissioV2.JSON_PROPERTY_DESTINATARIS,
  TransmissioV2.JSON_PROPERTY_ERROR,
  TransmissioV2.JSON_PROPERTY_ERROR_DATA,
  TransmissioV2.JSON_PROPERTY_ERROR_DESCRIPCIO,
  TransmissioV2.JSON_PROPERTY_JUSTIFICANT,
  TransmissioV2.JSON_PROPERTY_CERTIFICACIO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TransmissioV2 {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_EMISOR = "emisor";
  private String emisor;

  public static final String JSON_PROPERTY_ORGAN_GESTOR = "organGestor";
  private GenericInfo organGestor;

  public static final String JSON_PROPERTY_PROCEDIMENT = "procediment";
  private GenericInfo procediment;

  public static final String JSON_PROPERTY_NUM_EXPEDIENT = "numExpedient";
  private String numExpedient;

  public static final String JSON_PROPERTY_CONCEPTE = "concepte";
  private String concepte;

  public static final String JSON_PROPERTY_DESCRIPCIO = "descripcio";
  private String descripcio;

  public static final String JSON_PROPERTY_DATA_ENVIAMENT = "dataEnviament";
  private Long dataEnviament;

  public static final String JSON_PROPERTY_ESTAT = "estat";
  private GenericInfo estat;

  public static final String JSON_PROPERTY_DATA_ESTAT = "dataEstat";
  private Long dataEstat;

  public static final String JSON_PROPERTY_DOCUMENT = "document";
  private DocumentConsultaV2 document;

  public static final String JSON_PROPERTY_TITULAR = "titular";
  private PersonaConsultaV2 titular;

  public static final String JSON_PROPERTY_DESTINATARIS = "destinataris";
  private List<PersonaConsultaV2> destinataris;

  public static final String JSON_PROPERTY_ERROR = "error";
  private Boolean error;

  public static final String JSON_PROPERTY_ERROR_DATA = "errorData";
  private Long errorData;

  public static final String JSON_PROPERTY_ERROR_DESCRIPCIO = "errorDescripcio";
  private String errorDescripcio;

  public static final String JSON_PROPERTY_JUSTIFICANT = "justificant";
  private String justificant;

  public static final String JSON_PROPERTY_CERTIFICACIO = "certificacio";
  private String certificacio;

  public TransmissioV2() {
  }

  public TransmissioV2 id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Identificador de l&#39;enviament
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TransmissioV2 emisor(String emisor) {
    
    this.emisor = emisor;
    return this;
  }

   /**
   * Codi dir3 de l&#39;entitat emisora
   * @return emisor
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMISOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmisor() {
    return emisor;
  }


  @JsonProperty(JSON_PROPERTY_EMISOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmisor(String emisor) {
    this.emisor = emisor;
  }


  public TransmissioV2 organGestor(GenericInfo organGestor) {
    
    this.organGestor = organGestor;
    return this;
  }

   /**
   * Get organGestor
   * @return organGestor
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGAN_GESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GenericInfo getOrganGestor() {
    return organGestor;
  }


  @JsonProperty(JSON_PROPERTY_ORGAN_GESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganGestor(GenericInfo organGestor) {
    this.organGestor = organGestor;
  }


  public TransmissioV2 procediment(GenericInfo procediment) {
    
    this.procediment = procediment;
    return this;
  }

   /**
   * Get procediment
   * @return procediment
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROCEDIMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GenericInfo getProcediment() {
    return procediment;
  }


  @JsonProperty(JSON_PROPERTY_PROCEDIMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcediment(GenericInfo procediment) {
    this.procediment = procediment;
  }


  public TransmissioV2 numExpedient(String numExpedient) {
    
    this.numExpedient = numExpedient;
    return this;
  }

   /**
   * Número de l’expedient al que està associada la notificació
   * @return numExpedient
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUM_EXPEDIENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNumExpedient() {
    return numExpedient;
  }


  @JsonProperty(JSON_PROPERTY_NUM_EXPEDIENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumExpedient(String numExpedient) {
    this.numExpedient = numExpedient;
  }


  public TransmissioV2 concepte(String concepte) {
    
    this.concepte = concepte;
    return this;
  }

   /**
   * Concepte de la notificació
   * @return concepte
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONCEPTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConcepte() {
    return concepte;
  }


  @JsonProperty(JSON_PROPERTY_CONCEPTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConcepte(String concepte) {
    this.concepte = concepte;
  }


  public TransmissioV2 descripcio(String descripcio) {
    
    this.descripcio = descripcio;
    return this;
  }

   /**
   * Descripció de la notificació
   * @return descripcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescripcio() {
    return descripcio;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescripcio(String descripcio) {
    this.descripcio = descripcio;
  }


  public TransmissioV2 dataEnviament(Long dataEnviament) {
    
    this.dataEnviament = dataEnviament;
    return this;
  }

   /**
   * Data d&#39;enviament de la notificació
   * @return dataEnviament
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_ENVIAMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDataEnviament() {
    return dataEnviament;
  }


  @JsonProperty(JSON_PROPERTY_DATA_ENVIAMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataEnviament(Long dataEnviament) {
    this.dataEnviament = dataEnviament;
  }


  public TransmissioV2 estat(GenericInfo estat) {
    
    this.estat = estat;
    return this;
  }

   /**
   * Get estat
   * @return estat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GenericInfo getEstat() {
    return estat;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstat(GenericInfo estat) {
    this.estat = estat;
  }


  public TransmissioV2 dataEstat(Long dataEstat) {
    
    this.dataEstat = dataEstat;
    return this;
  }

   /**
   * Data en que s&#39;ha realitzat l&#39;enviament
   * @return dataEstat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_ESTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDataEstat() {
    return dataEstat;
  }


  @JsonProperty(JSON_PROPERTY_DATA_ESTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataEstat(Long dataEstat) {
    this.dataEstat = dataEstat;
  }


  public TransmissioV2 document(DocumentConsultaV2 document) {
    
    this.document = document;
    return this;
  }

   /**
   * Get document
   * @return document
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DocumentConsultaV2 getDocument() {
    return document;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocument(DocumentConsultaV2 document) {
    this.document = document;
  }


  public TransmissioV2 titular(PersonaConsultaV2 titular) {
    
    this.titular = titular;
    return this;
  }

   /**
   * Get titular
   * @return titular
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITULAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PersonaConsultaV2 getTitular() {
    return titular;
  }


  @JsonProperty(JSON_PROPERTY_TITULAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitular(PersonaConsultaV2 titular) {
    this.titular = titular;
  }


  public TransmissioV2 destinataris(List<PersonaConsultaV2> destinataris) {
    
    this.destinataris = destinataris;
    return this;
  }

  public TransmissioV2 addDestinatarisItem(PersonaConsultaV2 destinatarisItem) {
    if (this.destinataris == null) {
      this.destinataris = new ArrayList<>();
    }
    this.destinataris.add(destinatarisItem);
    return this;
  }

   /**
   * Persones representans, destinatàries de l&#39;enviament
   * @return destinataris
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESTINATARIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PersonaConsultaV2> getDestinataris() {
    return destinataris;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATARIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinataris(List<PersonaConsultaV2> destinataris) {
    this.destinataris = destinataris;
  }


  public TransmissioV2 error(Boolean error) {
    
    this.error = error;
    return this;
  }

   /**
   * Informa si s&#39;ha produït algun error en la notificació
   * @return error
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(Boolean error) {
    this.error = error;
  }


  public TransmissioV2 errorData(Long errorData) {
    
    this.errorData = errorData;
    return this;
  }

   /**
   * Data de l&#39;error
   * @return errorData
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getErrorData() {
    return errorData;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorData(Long errorData) {
    this.errorData = errorData;
  }


  public TransmissioV2 errorDescripcio(String errorDescripcio) {
    
    this.errorDescripcio = errorDescripcio;
    return this;
  }

   /**
   * Descripció de l&#39;error
   * @return errorDescripcio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorDescripcio() {
    return errorDescripcio;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
  }


  public TransmissioV2 justificant(String justificant) {
    
    this.justificant = justificant;
    return this;
  }

   /**
   * Url per a descarregar el justificant de registre
   * @return justificant
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JUSTIFICANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJustificant() {
    return justificant;
  }


  @JsonProperty(JSON_PROPERTY_JUSTIFICANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJustificant(String justificant) {
    this.justificant = justificant;
  }


  public TransmissioV2 certificacio(String certificacio) {
    
    this.certificacio = certificacio;
    return this;
  }

   /**
   * Url per a descarregar la Certificació generada al realitzar la compareixença de la notificació
   * @return certificacio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CERTIFICACIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificacio() {
    return certificacio;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICACIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificacio(String certificacio) {
    this.certificacio = certificacio;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransmissioV2 transmissioV2 = (TransmissioV2) o;
    return Objects.equals(this.id, transmissioV2.id) &&
        Objects.equals(this.emisor, transmissioV2.emisor) &&
        Objects.equals(this.organGestor, transmissioV2.organGestor) &&
        Objects.equals(this.procediment, transmissioV2.procediment) &&
        Objects.equals(this.numExpedient, transmissioV2.numExpedient) &&
        Objects.equals(this.concepte, transmissioV2.concepte) &&
        Objects.equals(this.descripcio, transmissioV2.descripcio) &&
        Objects.equals(this.dataEnviament, transmissioV2.dataEnviament) &&
        Objects.equals(this.estat, transmissioV2.estat) &&
        Objects.equals(this.dataEstat, transmissioV2.dataEstat) &&
        Objects.equals(this.document, transmissioV2.document) &&
        Objects.equals(this.titular, transmissioV2.titular) &&
        Objects.equals(this.destinataris, transmissioV2.destinataris) &&
        Objects.equals(this.error, transmissioV2.error) &&
        Objects.equals(this.errorData, transmissioV2.errorData) &&
        Objects.equals(this.errorDescripcio, transmissioV2.errorDescripcio) &&
        Objects.equals(this.justificant, transmissioV2.justificant) &&
        Objects.equals(this.certificacio, transmissioV2.certificacio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, emisor, organGestor, procediment, numExpedient, concepte, descripcio, dataEnviament, estat, dataEstat, document, titular, destinataris, error, errorData, errorDescripcio, justificant, certificacio);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransmissioV2 {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    emisor: ").append(toIndentedString(emisor)).append("\n");
    sb.append("    organGestor: ").append(toIndentedString(organGestor)).append("\n");
    sb.append("    procediment: ").append(toIndentedString(procediment)).append("\n");
    sb.append("    numExpedient: ").append(toIndentedString(numExpedient)).append("\n");
    sb.append("    concepte: ").append(toIndentedString(concepte)).append("\n");
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("    dataEnviament: ").append(toIndentedString(dataEnviament)).append("\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    dataEstat: ").append(toIndentedString(dataEstat)).append("\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    titular: ").append(toIndentedString(titular)).append("\n");
    sb.append("    destinataris: ").append(toIndentedString(destinataris)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorData: ").append(toIndentedString(errorData)).append("\n");
    sb.append("    errorDescripcio: ").append(toIndentedString(errorDescripcio)).append("\n");
    sb.append("    justificant: ").append(toIndentedString(justificant)).append("\n");
    sb.append("    certificacio: ").append(toIndentedString(certificacio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

