/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.DocumentConsultaV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.GenericInfo;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.PersonaConsultaV2;
import org.joda.time.DateTime;
/**
 * Llistat de les notificacions retornades
 */
@Schema(description = "Llistat de les notificacions retornades")


public class TransmissioV2 {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("emisor")
  private String emisor = null;

  @JsonProperty("organGestor")
  private GenericInfo organGestor = null;

  @JsonProperty("procediment")
  private GenericInfo procediment = null;

  @JsonProperty("numExpedient")
  private String numExpedient = null;

  @JsonProperty("concepte")
  private String concepte = null;

  @JsonProperty("descripcio")
  private String descripcio = null;

  @JsonProperty("dataEnviament")
  private DateTime dataEnviament = null;

  @JsonProperty("estat")
  private GenericInfo estat = null;

  @JsonProperty("dataEstat")
  private DateTime dataEstat = null;

  @JsonProperty("document")
  private DocumentConsultaV2 document = null;

  @JsonProperty("titular")
  private PersonaConsultaV2 titular = null;

  @JsonProperty("destinataris")
  private List<PersonaConsultaV2> destinataris = null;

  @JsonProperty("error")
  private Boolean error = null;

  @JsonProperty("errorData")
  private DateTime errorData = null;

  @JsonProperty("errorDescripcio")
  private String errorDescripcio = null;

  @JsonProperty("justificant")
  private String justificant = null;

  @JsonProperty("certificacio")
  private String certificacio = null;

  public TransmissioV2 id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador de l&#x27;enviament
   * @return id
  **/
  @Schema(description = "Identificador de l'enviament")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TransmissioV2 emisor(String emisor) {
    this.emisor = emisor;
    return this;
  }

   /**
   * Codi dir3 de l&#x27;entitat emisora
   * @return emisor
  **/
  @Schema(example = "A04003003", description = "Codi dir3 de l'entitat emisora")
  public String getEmisor() {
    return emisor;
  }

  public void setEmisor(String emisor) {
    this.emisor = emisor;
  }

  public TransmissioV2 organGestor(GenericInfo organGestor) {
    this.organGestor = organGestor;
    return this;
  }

   /**
   * Get organGestor
   * @return organGestor
  **/
  @Schema(description = "")
  public GenericInfo getOrganGestor() {
    return organGestor;
  }

  public void setOrganGestor(GenericInfo organGestor) {
    this.organGestor = organGestor;
  }

  public TransmissioV2 procediment(GenericInfo procediment) {
    this.procediment = procediment;
    return this;
  }

   /**
   * Get procediment
   * @return procediment
  **/
  @Schema(description = "")
  public GenericInfo getProcediment() {
    return procediment;
  }

  public void setProcediment(GenericInfo procediment) {
    this.procediment = procediment;
  }

  public TransmissioV2 numExpedient(String numExpedient) {
    this.numExpedient = numExpedient;
    return this;
  }

   /**
   * Número de l’expedient al que està associada la notificació
   * @return numExpedient
  **/
  @Schema(example = "123/2023", description = "Número de l’expedient al que està associada la notificació")
  public String getNumExpedient() {
    return numExpedient;
  }

  public void setNumExpedient(String numExpedient) {
    this.numExpedient = numExpedient;
  }

  public TransmissioV2 concepte(String concepte) {
    this.concepte = concepte;
    return this;
  }

   /**
   * Concepte de la notificació
   * @return concepte
  **/
  @Schema(example = "Concepte de la notificació", description = "Concepte de la notificació")
  public String getConcepte() {
    return concepte;
  }

  public void setConcepte(String concepte) {
    this.concepte = concepte;
  }

  public TransmissioV2 descripcio(String descripcio) {
    this.descripcio = descripcio;
    return this;
  }

   /**
   * Descripció de la notificació
   * @return descripcio
  **/
  @Schema(example = "Descripció de la notificació", description = "Descripció de la notificació")
  public String getDescripcio() {
    return descripcio;
  }

  public void setDescripcio(String descripcio) {
    this.descripcio = descripcio;
  }

  public TransmissioV2 dataEnviament(DateTime dataEnviament) {
    this.dataEnviament = dataEnviament;
    return this;
  }

   /**
   * Data d&#x27;enviament de la notificació
   * @return dataEnviament
  **/
  @Schema(description = "Data d'enviament de la notificació")
  public DateTime getDataEnviament() {
    return dataEnviament;
  }

  public void setDataEnviament(DateTime dataEnviament) {
    this.dataEnviament = dataEnviament;
  }

  public TransmissioV2 estat(GenericInfo estat) {
    this.estat = estat;
    return this;
  }

   /**
   * Get estat
   * @return estat
  **/
  @Schema(description = "")
  public GenericInfo getEstat() {
    return estat;
  }

  public void setEstat(GenericInfo estat) {
    this.estat = estat;
  }

  public TransmissioV2 dataEstat(DateTime dataEstat) {
    this.dataEstat = dataEstat;
    return this;
  }

   /**
   * Data en que s&#x27;ha realitzat l&#x27;enviament
   * @return dataEstat
  **/
  @Schema(description = "Data en que s'ha realitzat l'enviament")
  public DateTime getDataEstat() {
    return dataEstat;
  }

  public void setDataEstat(DateTime dataEstat) {
    this.dataEstat = dataEstat;
  }

  public TransmissioV2 document(DocumentConsultaV2 document) {
    this.document = document;
    return this;
  }

   /**
   * Get document
   * @return document
  **/
  @Schema(description = "")
  public DocumentConsultaV2 getDocument() {
    return document;
  }

  public void setDocument(DocumentConsultaV2 document) {
    this.document = document;
  }

  public TransmissioV2 titular(PersonaConsultaV2 titular) {
    this.titular = titular;
    return this;
  }

   /**
   * Get titular
   * @return titular
  **/
  @Schema(description = "")
  public PersonaConsultaV2 getTitular() {
    return titular;
  }

  public void setTitular(PersonaConsultaV2 titular) {
    this.titular = titular;
  }

  public TransmissioV2 destinataris(List<PersonaConsultaV2> destinataris) {
    this.destinataris = destinataris;
    return this;
  }

  public TransmissioV2 addDestinatarisItem(PersonaConsultaV2 destinatarisItem) {
    if (this.destinataris == null) {
      this.destinataris = new ArrayList<PersonaConsultaV2>();
    }
    this.destinataris.add(destinatarisItem);
    return this;
  }

   /**
   * Persones representans, destinatàries de l&#x27;enviament
   * @return destinataris
  **/
  @Schema(description = "Persones representans, destinatàries de l'enviament")
  public List<PersonaConsultaV2> getDestinataris() {
    return destinataris;
  }

  public void setDestinataris(List<PersonaConsultaV2> destinataris) {
    this.destinataris = destinataris;
  }

  public TransmissioV2 error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Informa si s&#x27;ha produït algun error en la notificació
   * @return error
  **/
  @Schema(example = "false", description = "Informa si s'ha produït algun error en la notificació")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public TransmissioV2 errorData(DateTime errorData) {
    this.errorData = errorData;
    return this;
  }

   /**
   * Data de l&#x27;error
   * @return errorData
  **/
  @Schema(description = "Data de l'error")
  public DateTime getErrorData() {
    return errorData;
  }

  public void setErrorData(DateTime errorData) {
    this.errorData = errorData;
  }

  public TransmissioV2 errorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
    return this;
  }

   /**
   * Descripció de l&#x27;error
   * @return errorDescripcio
  **/
  @Schema(example = "java.lang.NullPointerException", description = "Descripció de l'error")
  public String getErrorDescripcio() {
    return errorDescripcio;
  }

  public void setErrorDescripcio(String errorDescripcio) {
    this.errorDescripcio = errorDescripcio;
  }

  public TransmissioV2 justificant(String justificant) {
    this.justificant = justificant;
    return this;
  }

   /**
   * Url per a descarregar el justificant de registre
   * @return justificant
  **/
  @Schema(example = "http://localhost:8080/notibapi/interna/v2/justificant/00000000-0000-0000-0000-000000000000", description = "Url per a descarregar el justificant de registre")
  public String getJustificant() {
    return justificant;
  }

  public void setJustificant(String justificant) {
    this.justificant = justificant;
  }

  public TransmissioV2 certificacio(String certificacio) {
    this.certificacio = certificacio;
    return this;
  }

   /**
   * Url per a descarregar la Certificació generada al realitzar la compareixença de la notificació
   * @return certificacio
  **/
  @Schema(example = "http://localhost:8080/notibapi/interna/v2/certificacio/00000000-0000-0000-0000-000000000000", description = "Url per a descarregar la Certificació generada al realitzar la compareixença de la notificació")
  public String getCertificacio() {
    return certificacio;
  }

  public void setCertificacio(String certificacio) {
    this.certificacio = certificacio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransmissioV2 transmissioV2 = (TransmissioV2) o;
    return Objects.equals(this.id, transmissioV2.id) &&
        Objects.equals(this.emisor, transmissioV2.emisor) &&
        Objects.equals(this.organGestor, transmissioV2.organGestor) &&
        Objects.equals(this.procediment, transmissioV2.procediment) &&
        Objects.equals(this.numExpedient, transmissioV2.numExpedient) &&
        Objects.equals(this.concepte, transmissioV2.concepte) &&
        Objects.equals(this.descripcio, transmissioV2.descripcio) &&
        Objects.equals(this.dataEnviament, transmissioV2.dataEnviament) &&
        Objects.equals(this.estat, transmissioV2.estat) &&
        Objects.equals(this.dataEstat, transmissioV2.dataEstat) &&
        Objects.equals(this.document, transmissioV2.document) &&
        Objects.equals(this.titular, transmissioV2.titular) &&
        Objects.equals(this.destinataris, transmissioV2.destinataris) &&
        Objects.equals(this.error, transmissioV2.error) &&
        Objects.equals(this.errorData, transmissioV2.errorData) &&
        Objects.equals(this.errorDescripcio, transmissioV2.errorDescripcio) &&
        Objects.equals(this.justificant, transmissioV2.justificant) &&
        Objects.equals(this.certificacio, transmissioV2.certificacio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, emisor, organGestor, procediment, numExpedient, concepte, descripcio, dataEnviament, estat, dataEstat, document, titular, destinataris, error, errorData, errorDescripcio, justificant, certificacio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransmissioV2 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    emisor: ").append(toIndentedString(emisor)).append("\n");
    sb.append("    organGestor: ").append(toIndentedString(organGestor)).append("\n");
    sb.append("    procediment: ").append(toIndentedString(procediment)).append("\n");
    sb.append("    numExpedient: ").append(toIndentedString(numExpedient)).append("\n");
    sb.append("    concepte: ").append(toIndentedString(concepte)).append("\n");
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("    dataEnviament: ").append(toIndentedString(dataEnviament)).append("\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    dataEstat: ").append(toIndentedString(dataEstat)).append("\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    titular: ").append(toIndentedString(titular)).append("\n");
    sb.append("    destinataris: ").append(toIndentedString(destinataris)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorData: ").append(toIndentedString(errorData)).append("\n");
    sb.append("    errorDescripcio: ").append(toIndentedString(errorDescripcio)).append("\n");
    sb.append("    justificant: ").append(toIndentedString(justificant)).append("\n");
    sb.append("    certificacio: ").append(toIndentedString(certificacio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
