/*
 * API REST EXTERNA de Carpeta - Certificats
 * Plantilla de Serveis REST a implementar per servidors externs per des de Carpeta poder accedir a Certificats dels Ciutadans
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.carpeta.api.externa.client.certificats.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CertificatInfo
 */
@JsonPropertyOrder({
  CertificatInfo.JSON_PROPERTY_TE_CERTIFICAT,
  CertificatInfo.JSON_PROPERTY_ADMINISTRATION_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CertificatInfo {
  public static final String JSON_PROPERTY_TE_CERTIFICAT = "teCertificat";
  private Boolean teCertificat;

  public static final String JSON_PROPERTY_ADMINISTRATION_ID = "administrationId";
  private String administrationId;

  public CertificatInfo() {
  }

  public CertificatInfo teCertificat(Boolean teCertificat) {
    
    this.teCertificat = teCertificat;
    return this;
  }

   /**
   * Get teCertificat
   * @return teCertificat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TE_CERTIFICAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTeCertificat() {
    return teCertificat;
  }


  @JsonProperty(JSON_PROPERTY_TE_CERTIFICAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeCertificat(Boolean teCertificat) {
    this.teCertificat = teCertificat;
  }


  public CertificatInfo administrationId(String administrationId) {
    
    this.administrationId = administrationId;
    return this;
  }

   /**
   * Get administrationId
   * @return administrationId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADMINISTRATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdministrationId() {
    return administrationId;
  }


  @JsonProperty(JSON_PROPERTY_ADMINISTRATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdministrationId(String administrationId) {
    this.administrationId = administrationId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificatInfo certificatInfo = (CertificatInfo) o;
    return Objects.equals(this.teCertificat, certificatInfo.teCertificat) &&
        Objects.equals(this.administrationId, certificatInfo.administrationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teCertificat, administrationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificatInfo {\n");
    sb.append("    teCertificat: ").append(toIndentedString(teCertificat)).append("\n");
    sb.append("    administrationId: ").append(toIndentedString(administrationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

