<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="https://consultaApoderamientos.minhap.es/respuestaConsulta" xmlns:ns1="https://consultaApoderamientos.minhap.es/peticionConsulta" xmlns:ns0="https://consultaApoderamientos.minhap.es/soapfault" xmlns:impl="https://consultaApoderamientos.minhap.es/" targetNamespace="https://consultaApoderamientos.minhap.es/">
  <wsdl:types>
<schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="https://consultaApoderamientos.minhap.es/respuestaConsulta" xmlns:ns1="https://consultaApoderamientos.minhap.es/peticionConsulta" xmlns:ns0="https://consultaApoderamientos.minhap.es/soapfault" xmlns:impl="https://consultaApoderamientos.minhap.es/" xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.map.es/xml-schemas">
			<import namespace="https://consultaApoderamientos.minhap.es/peticionConsulta" schemaLocation="https://pre-reaws.redsara.es/reaCXFServer/services/reaCXFWSv2?xsd=peticionConsulta.xsd"/>
			<import namespace="https://consultaApoderamientos.minhap.es/respuestaConsulta" schemaLocation="https://pre-reaws.redsara.es/reaCXFServer/services/reaCXFWSv2?xsd=respuestaConsulta.xsd"/>
			<import namespace="https://consultaApoderamientos.minhap.es/soapfault" schemaLocation="https://pre-reaws.redsara.es/reaCXFServer/services/reaCXFWSv2?xsd=soapfault.xsd"/>
		</schema>
  </wsdl:types>
  <wsdl:message name="peticionConsulta">
    <wsdl:part element="ns1:PeticionConsulta" name="peticion">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="soapFault">
    <wsdl:part element="ns0:NotificacionesFault" name="soapFault">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="respuestaConsulta">
    <wsdl:part element="ns2:RespuestaConsulta" name="respuesta">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ConsultaAvanzadaPortType">
    <wsdl:operation name="consultaAvanzadaApoderamientos">
      <wsdl:input message="impl:peticionConsulta" name="PeticionConsulta">
    </wsdl:input>
      <wsdl:output message="impl:respuestaConsulta" name="RespuesConsulta">
    </wsdl:output>
      <wsdl:fault message="impl:soapFault" name="SoapFault">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultaAvanzadaBinding" type="impl:ConsultaAvanzadaPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaAvanzadaApoderamientos">
      <soap:operation soapAction="consultaAvanzadaApoderamientos" style="document"/>
      <wsdl:input>
        <soap:body parts="peticion" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="respuesta" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SoapFault">
        <soap:fault name="SoapFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ConsultaAvanzadaService">
    <wsdl:port binding="impl:ConsultaAvanzadaBinding" name="ConsultaAvanzadaPort">
      <soap:address location="https://pre-reaws.redsara.es/reaCXFServer/services/reaCXFWSv2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>