-- create index car_acces_pk_i on car_acces (accesid);
-- create index car_auditoria_pk_i on car_auditoria (auditoriaid);
-- create index car_avis_pk_i on car_avis (avisid);
create index car_avis_entitatid_fk_i on car_avis (entitatid);
-- create index car_enllaz_pk_i on car_enllaz (enllazid);
create index car_enllaz_entitatid_fk_i on car_enllaz (entitatid);
create index car_enllaz_nomid_fk_i on car_enllaz (nomid);
create index car_enllaz_urlid_fk_i on car_enllaz (urlid);
create index car_entitat_fitxercss_fk_i on car_entitat (fitxercss);
create index car_entitat_logintextid_fk_i on car_entitat (logintextid);
create index car_entitat_logolatfront_fk_i on car_entitat (logolateralfrontid);
create index car_entitat_nom_fk_i on car_entitat (nomid);
-- create index car_estadistica_pk_i on car_estadistica (estadisticaid);
-- create index car_fitxer_pk_i on car_fitxer (fitxerid);
-- create index car_log_pk_i on car_log (logid);
-- create index car_plugin_pk_i on car_plugin (pluginid);
create index car_plugin_logoid_fk_i on car_plugin (logoid);
-- create index car_pluginentitat_pk_i on car_pluginentitat (pluginentitatid);
create index car_plugent_pluginid_fk_i on car_pluginentitat (pluginid);
create index car_propglob_entitatid_fk_i on car_propietatglobal (entitatid);
create index car_seccio_descripcioid_fk_i on car_seccio (descripcioid);
create index car_seccio_iconaid_fk_i on car_seccio (iconaid);
-- create index car_usuari_pk_i on car_usuari (usuariid);
create index car_usuari_idiomaid_fk_i on car_usuari (idiomaid);
create index car_usuent_entitatid_fk_i on car_usuarientitat (entitatid);
