-- create index car_acces_pk_i on car_acces (accesid);
-- create index car_auditoria_pk_i on car_auditoria (auditoriaid);
-- create index car_avis_pk_i on car_avis (avisid);
create index car_avis_entitatid_fk_i on car_avis (entitatid);
-- create index car_ciutada_pk_i on car_ciutada (ciutadaid);
create index car_enllaz_nomid_fk_i on car_enllaz (nomid);
create index car_enllaz_urlid_fk_i on car_enllaz (urlid);
create index car_enllaz_logoid_fk_i on car_enllaz (logoid);
-- create index car_entitat_pk_i on car_entitat (entitatid);
create index car_entitat_descripcioid_fk_i on car_entitat (descripcioid);
create index car_entitat_logopeuback_fk_i on car_entitat (logopeubackid);
create index car_entitat_iconid_fk_i on car_entitat (iconid);
create index car_entitat_logintextid_fk_i on car_entitat (logintextid);
-- create index car_estadistica_pk_i on car_estadistica (estadisticaid);
-- create index car_fitxer_pk_i on car_fitxer (fitxerid);
-- create index car_log_pk_i on car_log (logid);
-- create index car_notificacioapp_pk_i on car_notificacioapp (notificacioappid);
create index car_notifica_missatgeid_fk_i on car_notificacioapp (missatgeid);
create index car_notifica_entitatid_fk_i on car_notificacioapp (entitatid);
create index car_plugin_nomid_fk_i on car_plugin (nomid);
create index car_plugin_titolllargid_fk_i on car_plugin (titolllargid);
create index car_plugin_logoid_fk_i on car_plugin (logoid);
create index car_plugent_pluginid_fk_i on car_pluginentitat (pluginid);
create index car_plugent_seccioid_fk_i on car_pluginentitat (seccioid);
create index car_faq_enunciatid_fk_i on car_preguntesfrequents (enunciatid);
create index car_faq_entitatid_fk_i on car_preguntesfrequents (entitatid);
create index car_faq_fitxer2id_fk_i on car_preguntesfrequents (fitxer2id);
-- create index car_propietatglobal_pk_i on car_propietatglobal (propietatglobalid);
-- create index car_seccio_pk_i on car_seccio (seccioid);
create index car_seccio_descripcioid_fk_i on car_seccio (descripcioid);
create index car_seccio_entitatid_fk_i on car_seccio (entitatid);
-- create index car_usuari_pk_i on car_usuari (usuariid);
create index car_usuari_idiomaid_fk_i on car_usuari (idiomaid);
create index car_usuent_usuariid_fk_i on car_usuarientitat (usuariid);
