/*
 * API REST EXTERNA de Carpeta
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.api.client.api;

import org.junit.Test;

import es.caib.carpeta.apiexterna.client.api.AccessosApi;
import es.caib.carpeta.apiexterna.client.model.PaginaAcces;
import es.caib.carpeta.apiexterna.client.services.ApiException;

import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccessosApi
 */
@Ignore
public class AccessosApiTest {

    private final AccessosApi api = new AccessosApi();

    /**
     * Retorna la llista d&#x60;accessos a CARPETA
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accessosTest() throws ApiException {
        String entitat = null;
        String inici = null;
        String fi = null;
        String idioma = null;
        PaginaAcces response = api.accessos(entitat, inici, fi, idioma);

        // TODO: test validations
    }
}
