/*
 * Carpeta - API REST - EXTERNA
 * API REST EXTERNA de Carpeta
 *
 * OpenAPI spec version: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.api.client.api;

import es.caib.carpeta.api.client.services.ApiClient;
import es.caib.carpeta.api.client.services.ApiException;
import es.caib.carpeta.api.client.services.auth.HttpBasicAuth;

import org.junit.Test;
import org.junit.Ignore;


/**
 * 
 */
/**
 * API tests for DefaultApi
 * @author anadal
 *
 */
@Ignore
public class DefaultApiTest {

    
    
    public static void main(String[] args) {
        DefaultApiTest dta = new DefaultApiTest();
        
        try {
            dta.accessosTest();
        } catch (ApiException e) {
            
            System.err.println("ERROR MSG: " +  e.getMessage());
            System.err.println("ERROR CODE: " +  e.getCode());
            System.err.println("ERROR BODY: " +  e.getResponseBody());
            System.err.println();
            System.err.println();
            System.err.println();
            
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    

    /**
     * Retorna la llista d&#x60;accessos a CARPETA
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accessosTest() throws ApiException {
        
        
        String basePath = "http://localhost:8080/carpetaapi/externa";
        boolean debugging = true;
        
        ApiClient ac = new ApiClient();
        ac.setBasePath(basePath);
        ac.setDebugging(debugging);
        
        //ac.setUsername("app");
        //ac.setPassword("app");
        

        
        HttpBasicAuth authentication = new HttpBasicAuth(); 
        authentication.setUsername("app");
        authentication.setPassword("app");
        ac.getAuthentications().put("basic", authentication);

   
        
        
        final DefaultApi api = new DefaultApi(ac);

        
        String inici = "2021-01-01";
        String fi = "2021-05-31";
        String entitat = "fundaciobit";
        String idioma = "ca";
        Object response = api.accessos(entitat, inici, fi, idioma);
        
        
        System.out.println( response.getClass());
        System.out.println( response.toString());
        
        
        
        System.out.println("ECHO => " + api.echo("HOLA CARACOLA"));

    }
}
