/*
 * API REST EXTERNA de Carpeta
 * Conjunt de Serveis REST de Carpeta per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.apiexterna.client.api;

import es.caib.carpeta.apiexterna.client.services.ApiClient;
import es.caib.carpeta.apiexterna.client.services.auth.HttpBasicAuth;
import es.caib.carpeta.apiexterna.client.model.CertificatBean;

import org.junit.Test;

import org.junit.Ignore;

/**
 * API tests for CertificatsApi
 */
@Ignore
public class CertificatsApiTest {

    public static void main(String[] args) {
        try {
            new CertificatsApiTest().certificatTest();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * Retorna un certificat a CARPETA
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void certificatTest() throws Exception {
        ApiClient client = new ApiClient();
        HttpBasicAuth auth = (HttpBasicAuth) client.getAuthentication("BasicAuth");
        auth.setUsername("carpetaapp");
        auth.setPassword("carpetaapp");

        client.setBasePath("http://localhost:8080/carpetaapi/externa");

        CertificatsApi api = new CertificatsApi(client);

        String dni = "99999999X";
        if (api.teCertificat(dni).isTeCertificat()) {
            String idioma = "ca";
            CertificatBean response = api.descarregarCertificat(dni, idioma);
            System.out.println("Tipus = " + response.getTipus());
            System.out.println("Nom Fitxer = " + response.getFitxer().getNom());
            System.out.println("Mime Fitxer = " + response.getFitxer().getMime());
            System.out.println("Length Fitxer = " + response.getFitxer().getLength());
            //System.out.println("Contingut Fitxer Codificat(byte[])= " + response.getFitxer().getBytes());
            System.out.println("Contingut Fitxer Codificat(base64)= " + response.getFitxer().getDataB64());
        } else {
            System.out.println("L'usuari amb DNI: " + dni + " no te certificats per aquest plugin.");

        }

        // TODO: test validations
    }
}
