/*
 * API REST EXTERNA de Carpeta
 * Conjunt de Serveis REST de Carpeta per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.apiexterna.client.api;

import es.caib.carpeta.apiexterna.client.services.ApiException;
import es.caib.carpeta.apiexterna.client.model.PaginaAcces;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EstadistiquesApi
 */
@Ignore
public class EstadistiquesApiTest {

    private final EstadistiquesApi api = new EstadistiquesApi();

    /**
     * Retorna la llista d&#x60;accessos a CARPETA
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accessos1Test() throws ApiException {
        String entitat = null;
        String inici = null;
        String fi = null;
        String idioma = null;
        PaginaAcces response = api.accessos1(entitat, inici, fi, idioma);

        // TODO: test validations
    }
}
