/*
 * API REST EXTERNA de Carpeta
 * Conjunt de Serveis REST de Carpeta per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.apiexterna.client.api;

import es.caib.carpeta.apiexterna.client.services.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificacionsApi
 */
@Ignore
public class NotificacionsApiTest {

    private final NotificacionsApi api = new NotificacionsApi();

    /**
     * Consulta si tenim donat d&#x27;alta el mòbil d&#x27;un ciutadà/empresa a partir del seu NIF.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void existciutadaTest() throws ApiException {
        String nif = null;
        String lang = null;
        Boolean response = api.existciutada(nif, lang);

        // TODO: test validations
    }
    /**
     * Envia un missatge al mòbil del ciutada a traves de l&#x27;App de Carpeta.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendmessageTest() throws ApiException {
        String nif = null;
        String title = null;
        String message = null;
        String lang = null;
        String response = api.sendmessage(nif, title, message, lang);

        // TODO: test validations
    }
}
