/*
 * API REST EXTERNA de Carpeta
 * Conjunt de Serveis REST de Carpeta per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * CertificatBytes
 */


public class CertificatBytes {
  @JsonProperty("bytes")
  private List<byte[]> bytes = null;

  @JsonProperty("byteArrayFile")
  private List<byte[]> byteArrayFile = null;

  public CertificatBytes bytes(List<byte[]> bytes) {
    this.bytes = bytes;
    return this;
  }

  public CertificatBytes addBytesItem(byte[] bytesItem) {
    if (this.bytes == null) {
      this.bytes = new ArrayList<byte[]>();
    }
    this.bytes.add(bytesItem);
    return this;
  }

   /**
   * Get bytes
   * @return bytes
  **/
  @Schema(description = "")
  public List<byte[]> getBytes() {
    return bytes;
  }

  public void setBytes(List<byte[]> bytes) {
    this.bytes = bytes;
  }

  public CertificatBytes byteArrayFile(List<byte[]> byteArrayFile) {
    this.byteArrayFile = byteArrayFile;
    return this;
  }

  public CertificatBytes addByteArrayFileItem(byte[] byteArrayFileItem) {
    if (this.byteArrayFile == null) {
      this.byteArrayFile = new ArrayList<byte[]>();
    }
    this.byteArrayFile.add(byteArrayFileItem);
    return this;
  }

   /**
   * Get byteArrayFile
   * @return byteArrayFile
  **/
  @Schema(description = "")
  public List<byte[]> getByteArrayFile() {
    return byteArrayFile;
  }

  public void setByteArrayFile(List<byte[]> byteArrayFile) {
    this.byteArrayFile = byteArrayFile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificatBytes certificatBytes = (CertificatBytes) o;
    return Objects.equals(this.bytes, certificatBytes.bytes) &&
        Objects.equals(this.byteArrayFile, certificatBytes.byteArrayFile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bytes, byteArrayFile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificatBytes {\n");
    
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("    byteArrayFile: ").append(toIndentedString(byteArrayFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
