/*
 * API REST EXTERNA de Carpeta
 * Conjunt de Serveis REST de Carpeta per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.carpeta.apiexterna.client.model.CertificatFileInfo;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CertificatBean
 */


public class CertificatBean {
  /**
   * Gets or Sets tipus
   */
  public enum TipusEnum {
    VALOR("VALOR"),
    FITXER("FITXER");

    private String value;

    TipusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TipusEnum fromValue(String text) {
      for (TipusEnum b : TipusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("tipus")
  private TipusEnum tipus = null;

  @JsonProperty("fitxer")
  private CertificatFileInfo fitxer = null;

  public CertificatBean tipus(TipusEnum tipus) {
    this.tipus = tipus;
    return this;
  }

   /**
   * Get tipus
   * @return tipus
  **/
  @Schema(description = "")
  public TipusEnum getTipus() {
    return tipus;
  }

  public void setTipus(TipusEnum tipus) {
    this.tipus = tipus;
  }

  public CertificatBean fitxer(CertificatFileInfo fitxer) {
    this.fitxer = fitxer;
    return this;
  }

   /**
   * Get fitxer
   * @return fitxer
  **/
  @Schema(description = "")
  public CertificatFileInfo getFitxer() {
    return fitxer;
  }

  public void setFitxer(CertificatFileInfo fitxer) {
    this.fitxer = fitxer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificatBean certificatBean = (CertificatBean) o;
    return Objects.equals(this.tipus, certificatBean.tipus) &&
        Objects.equals(this.fitxer, certificatBean.fitxer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipus, fitxer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificatBean {\n");
    
    sb.append("    tipus: ").append(toIndentedString(tipus)).append("\n");
    sb.append("    fitxer: ").append(toIndentedString(fitxer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
