/*
 * API REST EXTERNA de Carpeta
 * Conjunt de Serveis REST de Carpeta per ser accedits des de l'exterior
 *
 * OpenAPI spec version: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.carpeta.apiexterna.client.model.Acces;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * LlistatPaginatAcces
 */


public class LlistatPaginatAcces {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("page")
  private Integer page = null;

  @JsonProperty("page-size")
  private Integer pageSize = null;

  @JsonProperty("total-pages")
  private Integer totalPages = null;

  @JsonProperty("total-count")
  private Integer totalCount = null;

  @JsonProperty("items-returned")
  private Integer itemsReturned = null;

  @JsonProperty("next")
  private String next = null;

  @JsonProperty("date-download")
  private String dateDownload = null;

  @JsonProperty("data")
  private List<Acces> data = null;

  public LlistatPaginatAcces name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Nom descriptiu del que s&#x27;està retornant
   * @return name
  **/
  @Schema(required = true, description = "Nom descriptiu del que s'està retornant")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LlistatPaginatAcces page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Número pàgina. Comença per 1.
   * @return page
  **/
  @Schema(required = true, description = "Número pàgina. Comença per 1.")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public LlistatPaginatAcces pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Mida de pàgina
   * @return pageSize
  **/
  @Schema(required = true, description = "Mida de pàgina")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public LlistatPaginatAcces totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Número total de pàgines
   * @return totalPages
  **/
  @Schema(required = true, description = "Número total de pàgines")
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }

  public LlistatPaginatAcces totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Número total d&#x27;elements
   * @return totalCount
  **/
  @Schema(required = true, description = "Número total d'elements")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }

  public LlistatPaginatAcces itemsReturned(Integer itemsReturned) {
    this.itemsReturned = itemsReturned;
    return this;
  }

   /**
   * Numero d&#x27;elements retornats
   * @return itemsReturned
  **/
  @Schema(required = true, description = "Numero d'elements retornats")
  public Integer getItemsReturned() {
    return itemsReturned;
  }

  public void setItemsReturned(Integer itemsReturned) {
    this.itemsReturned = itemsReturned;
  }

  public LlistatPaginatAcces next(String next) {
    this.next = next;
    return this;
  }

   /**
   * Si hi ha més elements, llavors retorna la URL a la següent pàgina de dades.
   * @return next
  **/
  @Schema(description = "Si hi ha més elements, llavors retorna la URL a la següent pàgina de dades.")
  public String getNext() {
    return next;
  }

  public void setNext(String next) {
    this.next = next;
  }

  public LlistatPaginatAcces dateDownload(String dateDownload) {
    this.dateDownload = dateDownload;
    return this;
  }

   /**
   * Data i hora en que s&#x27;han retornat les dades. Format ISO-8601
   * @return dateDownload
  **/
  @Schema(required = true, description = "Data i hora en que s'han retornat les dades. Format ISO-8601")
  public String getDateDownload() {
    return dateDownload;
  }

  public void setDateDownload(String dateDownload) {
    this.dateDownload = dateDownload;
  }

  public LlistatPaginatAcces data(List<Acces> data) {
    this.data = data;
    return this;
  }

  public LlistatPaginatAcces addDataItem(Acces dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<Acces>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Elements retornats. Pot retornar un null o una llista buida si no hi ha elements.
   * @return data
  **/
  @Schema(description = "Elements retornats. Pot retornar un null o una llista buida si no hi ha elements.")
  public List<Acces> getData() {
    return data;
  }

  public void setData(List<Acces> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LlistatPaginatAcces llistatPaginatAcces = (LlistatPaginatAcces) o;
    return Objects.equals(this.name, llistatPaginatAcces.name) &&
        Objects.equals(this.page, llistatPaginatAcces.page) &&
        Objects.equals(this.pageSize, llistatPaginatAcces.pageSize) &&
        Objects.equals(this.totalPages, llistatPaginatAcces.totalPages) &&
        Objects.equals(this.totalCount, llistatPaginatAcces.totalCount) &&
        Objects.equals(this.itemsReturned, llistatPaginatAcces.itemsReturned) &&
        Objects.equals(this.next, llistatPaginatAcces.next) &&
        Objects.equals(this.dateDownload, llistatPaginatAcces.dateDownload) &&
        Objects.equals(this.data, llistatPaginatAcces.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, page, pageSize, totalPages, totalCount, itemsReturned, next, dateDownload, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LlistatPaginatAcces {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    itemsReturned: ").append(toIndentedString(itemsReturned)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    dateDownload: ").append(toIndentedString(dateDownload)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
