/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.api;

import org.fundaciobit.pluginsib.carpetafront.notib2client.services.ApiException;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.Arxiu;
import java.util.Date;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaV2;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConsultaV2Api
 */
public class ConsultaV2ApiTest {

    private final ConsultaV2Api api = new ConsultaV2Api();

    /**
     * Consulta totes les comunicacions d&#39;un titular donat el seu dni
     *
     * Retorna informació de totes les comunicacions d&#39;un titular, i el seu estat
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comunicacionsByTitularTest() throws ApiException {
        //
        //String dniTitular = null;
        //
        //Date dataInicial = null;
        //
        //Date dataFinal = null;
        //
        //Boolean visibleCarpeta = null;
        //
        //String lang = null;
        //
        //Integer pagina = null;
        //
        //Integer mida = null;
        //
        //RespostaConsultaV2 response = api.comunicacionsByTitular(dniTitular, dataInicial, dataFinal, visibleCarpeta, lang, pagina, mida);

        // TODO: test validations
    }
    /**
     * Consulta totes les comunicacions llegides d&#39;un titular donat el seu dni
     *
     * Retorna informació sobre les comunicacions ja llegides d&#39;un titular, i el seu estat
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comunicacionsLlegidesByTitularTest() throws ApiException {
        //
        //String dniTitular = null;
        //
        //Date dataInicial = null;
        //
        //Date dataFinal = null;
        //
        //Boolean visibleCarpeta = null;
        //
        //String lang = null;
        //
        //Integer pagina = null;
        //
        //Integer mida = null;
        //
        //RespostaConsultaV2 response = api.comunicacionsLlegidesByTitular(dniTitular, dataInicial, dataFinal, visibleCarpeta, lang, pagina, mida);

        // TODO: test validations
    }
    /**
     * Consulta totes les comunicacions pendents (no llegides) d&#39;un titular donat el seu dni
     *
     * Retorna informació sobre les comunicacions pendents d&#39;un titular, i el seu estat
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void comunicacionsPendentsByTitularTest() throws ApiException {
        //
        //String dniTitular = null;
        //
        //Date dataInicial = null;
        //
        //Date dataFinal = null;
        //
        //Boolean visibleCarpeta = null;
        //
        //String lang = null;
        //
        //Integer pagina = null;
        //
        //Integer mida = null;
        //
        //RespostaConsultaV2 response = api.comunicacionsPendentsByTitular(dniTitular, dataInicial, dataFinal, visibleCarpeta, lang, pagina, mida);

        // TODO: test validations
    }
    /**
     * Obté la certificació d&#39;una notificació
     *
     * Retorna el document de certificació de lectura de la notificació. El contingut del document està en Base64
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCertificacioTest() throws ApiException {
        //
        //Long enviamentId = null;
        //
        //Arxiu response = api.getCertificacio(enviamentId);

        // TODO: test validations
    }
    /**
     * Obté el document d&#39;una notificació
     *
     * Retorna el document de la notificació. El contingut del document està en Base64
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDocumentTest() throws ApiException {
        //
        //Long notificacioId = null;
        //
        //Arxiu response = api.getDocument(notificacioId);

        // TODO: test validations
    }
    /**
     * Obté el justificant d&#39;una comunicació
     *
     * Retorna el document de justificant de entrega de la comunicació. El contingut del document està en Base64
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJustificantTest() throws ApiException {
        //
        //Long enviamentId = null;
        //
        //Arxiu response = api.getJustificant(enviamentId);

        // TODO: test validations
    }
    /**
     * Consulta totes les notificacions d&#39;un titular donat el seu dni
     *
     * Retorna informació de totes les notificacions d&#39;un titular, i el seu estat
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void notificacionsByTitularTest() throws ApiException {
        //
        //String dniTitular = null;
        //
        //Date dataInicial = null;
        //
        //Date dataFinal = null;
        //
        //Boolean visibleCarpeta = null;
        //
        //String lang = null;
        //
        //Integer pagina = null;
        //
        //Integer mida = null;
        //
        //RespostaConsultaV2 response = api.notificacionsByTitular(dniTitular, dataInicial, dataFinal, visibleCarpeta, lang, pagina, mida);

        // TODO: test validations
    }
    /**
     * Consulta totes les notificacions llegides d&#39;un titular donat el seu dni
     *
     * Retorna informació sobre les notificacions ja llegides d&#39;un titular, i el seu estat
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void notificacionsLlegidesByTitularTest() throws ApiException {
        //
        //String dniTitular = null;
        //
        //Date dataInicial = null;
        //
        //Date dataFinal = null;
        //
        //Boolean visibleCarpeta = null;
        //
        //String lang = null;
        //
        //Integer pagina = null;
        //
        //Integer mida = null;
        //
        //RespostaConsultaV2 response = api.notificacionsLlegidesByTitular(dniTitular, dataInicial, dataFinal, visibleCarpeta, lang, pagina, mida);

        // TODO: test validations
    }
    /**
     * Consulta totes les notificacions pendents (no llegides) d&#39;un titular donat el seu dni
     *
     * Retorna informació sobre les notificacions pendents d&#39;un titular, i el seu estat
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void notificacionsPendentsByTitularTest() throws ApiException {
        //
        //String dniTitular = null;
        //
        //Date dataInicial = null;
        //
        //Date dataFinal = null;
        //
        //Boolean visibleCarpeta = null;
        //
        //String lang = null;
        //
        //Integer pagina = null;
        //
        //Integer mida = null;
        //
        //RespostaConsultaV2 response = api.notificacionsPendentsByTitular(dniTitular, dataInicial, dataFinal, visibleCarpeta, lang, pagina, mida);

        // TODO: test validations
    }
}
