/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.api;

import org.fundaciobit.pluginsib.carpetafront.notib2client.model.AppInfo;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for InformaciNotibApi
 */
@Ignore
public class InformaciNotibApiTest {

    private final InformaciNotibApi api = new InformaciNotibApi();

    /**
     * Consulta la informació de la API
     *
     * Retorna la data i la versió de la API REST Interna Notib
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAppInfoTest() throws Exception {
        AppInfo response = api.getAppInfo();

        // TODO: test validations
    }
}
