/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.api;

import org.fundaciobit.pluginsib.carpetafront.notib2client.services.ApiException;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.AppInfo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InformaciNotibApi
 */
public class InformaciNotibApiTest {

    private final InformaciNotibApi api = new InformaciNotibApi();

    /**
     * Consulta la informació de la API
     *
     * Retorna la data i la versió de la API REST Interna Notib
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAppInfoTest() throws ApiException {
        //
        //AppInfo response = api.getAppInfo();

        // TODO: test validations
    }
}
