/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * OpenAPI spec version: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.carpetafront.notib2client.api;

import org.fundaciobit.pluginsib.carpetafront.notib2client.model.DadesConsulta;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.NotificacioV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.PermisConsulta;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaAltaV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaDadesRegistreV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaEstatEnviamentV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaEstatNotificacioV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaJustificantEnviament;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for NotificacioV2Api
 */
@Ignore
public class NotificacioV2ApiTest {

    private final NotificacioV2Api api = new NotificacioV2Api();

    /**
     * Registra i envia la notificació a Notific@.
     *
     * Retorna una llista amb els codis dels enviaments creats per poder consultar el seu estat posteriorment
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void altaTest() throws Exception {
        NotificacioV2 body = null;
        RespostaAltaV2 response = api.alta(body);

        // TODO: test validations
    }
    /**
     * Genera el justificant i consulta la informació del registre d&#x27;una notificació.
     *
     * Retorna la informació del registre i el justificant d&#x27;una notificació dins Notib.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consultaDadesRegistreTest() throws Exception {
        DadesConsulta body = null;
        RespostaConsultaDadesRegistreV2 response = api.consultaDadesRegistre(body);

        // TODO: test validations
    }
    /**
     * Consulta la informació de l&#x27;estat d&#x27;un enviament dins Notific@
     *
     * Retorna la informació sobre l&#x27;estat de l&#x27;enviament dins Notific@.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consultaEstatEnviamentTest() throws Exception {
        String referencia = null;
        RespostaConsultaEstatEnviamentV2 response = api.consultaEstatEnviament(referencia);

        // TODO: test validations
    }
    /**
     * Consulta de la informació d&#x27;una notificació
     *
     * Retorna la informació sobre l&#x27;estat de l&#x27;enviament dins Notib o Notific@
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consultaEstatNotificacioTest() throws Exception {
        String identificador = null;
        RespostaConsultaEstatNotificacioV2 response = api.consultaEstatNotificacio(identificador);

        // TODO: test validations
    }
    /**
     * Consulta el justificant de l&#x27;enviament d&#x27;una notificació
     *
     * Retorna el document PDF amb el justificant de l&#x27;enviament de la notificació
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void consultaJustificantV2Test() throws Exception {
        String identificador = null;
        RespostaConsultaJustificantEnviament response = api.consultaJustificantV2(identificador);

        // TODO: test validations
    }
    /**
     * Donar permis de consulta a un usuari sobre un procediment
     *
     * Aquest mètode permet donar el permís de consulta a un usuari específic
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void donarPermisConsultaV2Test() throws Exception {
        PermisConsulta body = null;
        String response = api.donarPermisConsultaV2(body);

        // TODO: test validations
    }
}
