/*
 * API Interna NOTIB
 * API Interna de NOTIB
 *
 * The version of the OpenAPI document: v2.0
 * Contact: limit@limit.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.carpetafront.notib2client.api;

import org.fundaciobit.pluginsib.carpetafront.notib2client.services.ApiException;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.DadesConsulta;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.NotificacioV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.PermisConsulta;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaAltaV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaDadesRegistreV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaEstatEnviamentV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaEstatNotificacioV2;
import org.fundaciobit.pluginsib.carpetafront.notib2client.model.RespostaConsultaJustificantEnviament;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificacioV2Api
 */
public class NotificacioV2ApiTest {

    private final NotificacioV2Api api = new NotificacioV2Api();

    /**
     * Registra i envia la notificació a Notific@.
     *
     * Retorna una llista amb els codis dels enviaments creats per poder consultar el seu estat posteriorment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void altaTest() throws ApiException {
        //
        //NotificacioV2 notificacioV2 = null;
        //
        //RespostaAltaV2 response = api.alta(notificacioV2);

        // TODO: test validations
    }
    /**
     * Genera el justificant i consulta la informació del registre d&#39;una notificació.
     *
     * Retorna la informació del registre i el justificant d&#39;una notificació dins Notib.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultaDadesRegistreTest() throws ApiException {
        //
        //DadesConsulta dadesConsulta = null;
        //
        //RespostaConsultaDadesRegistreV2 response = api.consultaDadesRegistre(dadesConsulta);

        // TODO: test validations
    }
    /**
     * Consulta la informació de l&#39;estat d&#39;un enviament dins Notific@
     *
     * Retorna la informació sobre l&#39;estat de l&#39;enviament dins Notific@.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultaEstatEnviamentTest() throws ApiException {
        //
        //String referencia = null;
        //
        //RespostaConsultaEstatEnviamentV2 response = api.consultaEstatEnviament(referencia);

        // TODO: test validations
    }
    /**
     * Consulta de la informació d&#39;una notificació
     *
     * Retorna la informació sobre l&#39;estat de l&#39;enviament dins Notib o Notific@
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultaEstatNotificacioTest() throws ApiException {
        //
        //String identificador = null;
        //
        //RespostaConsultaEstatNotificacioV2 response = api.consultaEstatNotificacio(identificador);

        // TODO: test validations
    }
    /**
     * Consulta el justificant de l&#39;enviament d&#39;una notificació
     *
     * Retorna el document PDF amb el justificant de l&#39;enviament de la notificació
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultaJustificantV2Test() throws ApiException {
        //
        //String identificador = null;
        //
        //RespostaConsultaJustificantEnviament response = api.consultaJustificantV2(identificador);

        // TODO: test validations
    }
    /**
     * Donar permis de consulta a un usuari sobre un procediment
     *
     * Aquest mètode permet donar el permís de consulta a un usuari específic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void donarPermisConsultaV2Test() throws ApiException {
        //
        //PermisConsulta permisConsulta = null;
        //
        //String response = api.donarPermisConsultaV2(permisConsulta);

        // TODO: test validations
    }
}
