/*
 * API REST INTERNA de Carpeta
 * Conjunt de Serveis REST de Carpeta per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: governdigital.carpeta@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.carpeta.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Codi resultat de l&#39;operació
 */
public enum SendMessageResultCode {
  
  OK("OK"),
  
  UNKNOWN_ERROR("UNKNOWN_ERROR"),
  
  NOTIFICATION_CODE_DO_NOT_EXIST("NOTIFICATION_CODE_DO_NOT_EXIST"),
  
  NOTIFICATION_CODE_DISABLED("NOTIFICATION_CODE_DISABLED"),
  
  ENTITYCODE_DO_NOT_EXIST("ENTITYCODE_DO_NOT_EXIST"),
  
  ENTITY_DISABLED("ENTITY_DISABLED"),
  
  PLUGIN_DISABLED("PLUGIN_DISABLED"),
  
  PLUGIN_ENTITY_DO_NOT_EXIST("PLUGIN_ENTITY_DO_NOT_EXIST"),
  
  PLUGIN_ENTITY_DISABLED("PLUGIN_ENTITY_DISABLED"),
  
  CITIZEN_DO_NOT_EXIST("CITIZEN_DO_NOT_EXIST"),
  
  ERROR_SENDING_NOTIFICATION("ERROR_SENDING_NOTIFICATION");

  private String value;

  SendMessageResultCode(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SendMessageResultCode fromValue(String value) {
    for (SendMessageResultCode b : SendMessageResultCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

