/*
 * Carpeta - API Rest - Externa
 * Carpeta Java EE 8 i JBOSS 7.2
 *
 * OpenAPI spec version: 1.1.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package es.caib.carpeta.api.client.services.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
